- EOS/breakout/actual_eos.f90
- EOS/gamma_law_general/actual_eos.F90
- EOS/helmholtz/actual_eos.F90
- EOS/multigamma/actual_eos.f90
- EOS/polytrope/actual_eos.f90
- EOS/stellarcollapse/actual_eos.f90
- EOS/ztwd/actual_eos.f90
This was really only a problem for helmholtz, since `actual_eos_module` contained a `private` statement, but to be safe, make `eos_name` public in general.
> Explicitly declare eos_name as public variable

- networks/aprox21/actual_rhs.f90
In particular, the additional terms for 56Fe and 56Cr are now added.  
From Aron:
```
I have isolated the fixes for the RHS of the approx21 network. The
missing terms are the reactions to 56Fe and 56Cr. The latter one
represents the neutron rich material in the approx21 network. Therefore
neutron enrichment does not take place in the Boxlib version of the
network.
The additional terms for the reactions to 56Fe and 56Cr have been
obtained by comparing the approx21 network in Boxlib with the one
provided by F. Timmes
```
> fix from Aron Michel (HITS) that fills in missing reactions.

- integration/BS/stiff_ode.F90
With the scheme we now have for switching integrators on a failure,
we simply want to abort the integration when this occurs, not crash.
> Do not crash if non-convergence occurs in a BS step

- CHANGES
- integration/BS/_parameters
- integration/BS/bs_type.F90
- integration/VODE/vode_rhs.f90
- integration/VODE/vode_type.f90
- integration/_parameters
This brings VODE into alignment with BS regarding what checks we apply to the integration state.
It also makes the maximum temperature for reactions an adjustable input parameter, rather than being hardcoded at 10^11 K.
Fixes #45 
Fixes #46
> Clean up the consistency checking in the integration state

- CHANGES
- networks/aprox19/_parameters
- networks/aprox21/_parameters
The change was made at some point to use the numerical Jacobian for
these networks, because we learned that the hardwired Jacobian has
some missing terms. However, the numerical Jacobian in practice seems
to have big problems -- it can cause VODE to complete the integration
with crazy states that have X >> 1, but VODE thinks it is converged.
We also see NaN's in the Jacobian when we examine it. So we are going
to revert to the analytical Jacobian default -- this seems to work better.
> Do not rely on the numerical Jacobian for aprox19/aprox21

- EOS/helmholtz/actual_eos.F90
Rather than having every MPI rank read the Helmholtz table, have only the IO processor do so, and then broadcast the data to other processors. This can help significantly reduce the EOS initialization time when there are many ranks.
This addresses Castro issue 172.
This depends on AMReX pull request 138.
> Broadcast Helmholtz table to all processors

- networks/aprox13/actual_rhs.f90
- networks/aprox19/actual_rhs.f90
- networks/aprox21/actual_rhs.f90
- networks/iso7/actual_rhs.f90
`esum()` has no benefit for sums of 1 or 2 terms
> remove esum() for sums of 1 or 2 terms

- unit_test/burn_cell/burn_cell.py
Set burn_cell.py to look into 'runprefix_output' for the files required for plotting.
> Set burn_cell.py to look into 'runprefix_output' 

- integration/integrator.F90
Instead of swapping integrators at a fixed tolerance, we will instead hold the integrator constant and first attempt loosening the tolerance when a burn fails. This allows for a more consistent evolution when a burn fails, at the expense of a looser tolerance.
Closes #95
> Modify burn retry strategy to stick with current integrator as long as possible

- networks/subch/actual_network.f90
- networks/subch/actual_rhs.f90
This just moves the subroutine ener_gener_rate into the actual_rhs module for the subch network to match convention.
> Move ener_gener_rate into actual_rhs for subch network.

- EOS/helmholtz/actual_eos.F90
- GMicrophysics.mak
- interfaces/GPackage.mak
- interfaces/eos_type.F90
This PR will not declare composition derivative components of `eos_t` unless `EXTRA_THERMO` is defined.
Previously, we would not yield a compiler error if we tried accessing the composition derivatives without `EXTRA_THERMO`, introducing undefined results and, when compiling with OpenMP, silent NaNs.
We should use the `eos_t.F90` here in Maestro to avoid problems like this.
This changes one instance of `if EXTRA_THERMO` to `ifdef EXTRA_THERMO` in `helmholtz/actual_eos.F90` to conform to all other ifdef statements in which `EXTRA_THERMO` appears.
> Do not define extra thermo components of eos_t ifndef EXTRA_THERMO

- interfaces/burn_type.F90
- interfaces/eos_type.F90
- unit_test/eos.F90
This updates the burn type and eos type in /interfaces for CUDA managed memory and adds AMREX_DEVICE to the appropriate subroutines.
Allocating and initializing the eos module variables is now in unit_test/eos.F90.
> Update interfaces for CUDA.

- networks/aprox13/actual_rhs.f90
- networks/aprox19/actual_rhs.f90
- networks/aprox21/actual_rhs.f90
- networks/iso7/actual_rhs.f90
- util/BLAS/GPackage.mak
- util/BLAS/Make.package
- util/BLAS/blas_module.F90
- util/LINPACK/GPackage.mak
- util/LINPACK/Make.package
- util/LINPACK/linpack_module.F90
- util/microphysics_math.F90
This adds the CUDA-marked up utility modules for BLAS and LINPACK from cudadevice.
This also adds the specialized esums to microphysics math and replaces `esum` in the aprox networks with the specialized versions.
> Add utility modules and specialized esums

- util/esum.py
- util/esum_module.F90
To avoid the possibility of compilers optimizing out the key statements in esum, mark local variables as volatile (from the F2003 standard).
> Mark some variables as volatile to avoid compiler optimizations

- EOS/stellarcollapse/actual_eos.F90
- EOS/stellarcollapse/eos_aux_data.f90
- interfaces/eos_type.F90
These changes fixed the energy shift bug in the Stellar Collapse EOS and also add input checking to detect which eos type variables to convert to table units depending on the eos input type.
Adds functionality to the EOS type module to support checking what input variables different input types support.
The Stellar Collapse energy shift bug was that previously we were converting to table units by subtracting the energy shift from the input internal energy. And to convert from table units we added the energy shift.
However, the Stellar Collapse tables were designed such that the energy shift ensures the input specific internal energy is always positive. This requires us to add the energy shift to convert to table units and subtract the energy shift to convert from table units.
For an …
> Fix bug in stellarcollapse EOS and improve input sanitation

- screening/screen.F90
blanket private statements break the script
> fix screening for CUDA

- integration/VODE90/cuVODE/linear_algebra_modules/blas_module.F90
- integration/VODE90/cuVODE/source/cuvode.F90
- integration/VODE90/cuVODE/source/cuvode_dacopy.F90
- integration/VODE90/cuVODE/source/cuvode_dvjac.F90
- integration/VODE90/cuVODE/source/cuvode_dvnlsd.F90
- integration/VODE90/cuVODE/source/cuvode_dvstep.F90
This works around a PGI 19.1+ bug compiling blas_module.F90 for CUDA.
> Remove dcopyn, explicitly write out array copies

- CHANGES.md
- networks/iso7/actual_rhs.F90
The screening term on O16 + O16 was incorrectly being applied to the C12 + O16 rate.
> Fixing indexing in iso7 screening

- neutrinos/sneut5.F90
These were removed in the beginning of Microphysics (bdef8c8) because at the time, we had not ported the analytic Jacobian from Frank Timmes' network, and instead were relying on VODE's numerical Jacobian, and there was no need to evaluate the derivatives for calculating the RHS. However, we later inserted the analytic Jacobians, including the contribution from the neutrinos, and then centralized on a neutrino source file, but did not restore the derivatives by abar and zbar, so the Jacobian was not including all of the relevant terms.
A later pull request will compensate for the performance hit this implies in the RHS, but we should deal with the functionality issue first.
> Replace the derivatives by abar and zbar in the neutrino term

- networks/ECSN/actual_rhs.F90
- networks/aprox13/actual_rhs.F90
- networks/aprox19/actual_rhs.F90
- networks/aprox21/actual_rhs.F90
- networks/ignition_reaclib/C-burn-simple/actual_rhs.F90
- networks/ignition_reaclib/C-test/actual_rhs.F90
- networks/ignition_reaclib/URCA-simple/actual_rhs.F90
- networks/iso7/actual_rhs.F90
- networks/nova/actual_rhs.f90
- networks/sn160/actual_rhs.F90
- networks/subch/actual_rhs.F90
- networks/subch2/actual_rhs.F90
The neutrino cooling term returns d(S_nu)/dT, d(S_nu)/d(Abar), and d(S_nu)/d(Zbar). Since we're interested in dE/dY_j, we need to use the chain rule to obtain -dE/dY_j = d(Abar)/dY_j * d(S_nu)/d(Abar) + d(Zbar)/dY_j * d(S_nu)/d(Zbar). The latter term is correctly computed by all networks, since an analytic calculation reveals that d(Zbar)/dY_j is (Z_j - Zbar) * Abar. For the former term, it can either be -Abar^2, or (A_j - Abar) * Abar, depending on whether you enforce that sum(X) = 1 prior to taking the derivative.
Out of Frank Timmes' public networks as of this date, the 7 isotope and 34 isotope networks do it the way recommended by this PR, but the 13, 19 and 21 isotope networks do it the other way (the way that Microphysics does it, prior to this PR).
> Modify the Jacobian contributions from the neutrino cooling

- integration/VODE/vode_integrator_sdc.f90
- integration/VODE90/actual_integrator_simplified_sdc.F90
When calling `vode_to_sdc` at the end of the simplified SDC integration with VODE and VODE90, we were previously passing `time` as the time step to update unevolved variables rho and rho*u.
`time` was the simulation time in Castro at the start of the burner call, not the ODE integration end time. The difference is that the ODE integration end time is just the time advanced by the ODE integrator relative to its starting time of 0. So this is the reaction timestep from Castro that we should use to apply the advection sources to rho and rho*u before returning to Castro.
> For simplified SDC, apply advection sources at end of integration using integration time

- CHANGES.md
- integration/BS/bs_integrator.F90
- integration/BS/bs_integrator_sdc.F90
- integration/VODE90/vode_integrator_simplified_sdc.F90
- integration/VODE90/vode_integrator_true_sdc.F90
- integration/integrator_sdc.F90
- interfaces/sdc_type.F90
This is in conjunction with #695 for Castro. MAESTROeX will need a minor update since the `sdc_t` has had a field added.
> Enable the retry mechanism for simplified SDC

- integration/VODE/cuVODE/source/rpar.F90.template
- integration/VODE/vode_type_simplified_sdc.F90
VODE's simplified SDC interface assumed that `nspec_evolve == nspec` by accessing `nspec` species elements of `burn_t % ydot` and `burn_t % jac` in the `rhs_to_vode` and `jac_to_vode` subroutines.
For simplified SDC, the integrator integrates all the species along with the energy terms, the unevolved species just see the advective sources. So accessing `nspec` elements from `ydot` and `jac` like we were doing yielded incorrect right hand side terms seen by the integrator for the unevolved species.
This is a likely culprit for the `NaN` in electron fraction observed in MAESTROeX simplified SDC tests with `ignition_simple`.
The BS integrator did this correctly.
> Bugfixes for VODE's simplified SDC interface when nspec_evolve != nspec

- EOS/gamma_law/Make.package
- EOS/gamma_law/_parameters
- EOS/gamma_law/gamma_law.F90
- EOS/rad_power_law/Make.package
- EOS/rad_power_law/_parameters
- EOS/rad_power_law/rad_power_law.F90
- interfaces/Make.package
- interfaces/burner.F90
- interfaces/conductivity.F90
- interfaces/eos.F90
- opacity/Readme
- opacity/breakout/Make.package
- opacity/breakout/opacity_table_module.F90
- opacity/rad_power_law/Make.package
- opacity/rad_power_law/_parameters
- opacity/rad_power_law/opacity_table_module.F90
- viscosity/constant/Make.package
- viscosity/constant/_parameters
- viscosity/constant/constant_viscosity.f90
This includes the `opacity` and `viscosity` directories, as well as two toy equations of state (`gamma_law` and `rad_power_law`). A few interfaces are updated, including the EOS, burner, and conductivity.
> Copy over some microphysics from Castro

- interfaces/network.F90
- networks/general_null/gammalaw_aux.net
- networks/general_null/network.template
- networks/general_null/network_header.template
- networks/general_null/network_properties.template
- networks/general_null/write_network.py
this adds the aux names to the C++ header, and 1/aion to all of the autogenerated net stuff (including general_null).
Closes #252 #254
> add the aux names and 1/aion to the network auto generated stuff

- Make.CVODE
- Make.Microphysics
- Make.Microphysics_extern
- integration/Make.package
- networks/Make.package
- networks/general_null/Make.package
This reorganizes the makefiles to separate out the bits that include all of the various Microphysics modules.  This will make it easier for Castro to simply include `Make.Microphysics_extern` instead of duplicating it all on its own.
> restructure makefiles

- EOS/breakout/actual_eos.F90
- EOS/breakout/actual_eos.H
- EOS/gamma_law/actual_eos.H
- EOS/gamma_law/gamma_law.F90
- EOS/gamma_law_general/actual_eos.F90
- EOS/gamma_law_general/actual_eos.H
- EOS/helmholtz/actual_eos.F90
- EOS/helmholtz/actual_eos.H
- EOS/multigamma/actual_eos.F90
- EOS/multigamma/actual_eos.H
- EOS/polytrope/actual_eos.F90
- EOS/polytrope/actual_eos.H
- EOS/rad_power_law/actual_eos.H
- EOS/rad_power_law/rad_power_law.F90
- EOS/stellarcollapse/actual_eos.F90
- EOS/ztwd/actual_eos.F90
- EOS/ztwd/actual_eos.H
- unit_test/test_eos_C/main.cpp
We can now query an EOS to see if it supports a given input mode
> add is_input_valid

- integration/VODE/vode_dvhin.H
- integration/VODE/vode_dvjac.H
- integration/VODE/vode_dvnlsd.H
- integration/VODE/vode_dvode.H
- integration/VODE/vode_dvstep.H
- integration/VODE/vode_rhs.H
- integration/VODE/vode_type.H
- interfaces/burn_type.H
- networks/powerlaw/actual_network.H
This fixes some minor issues with loop bounds as well as some small cosmetic changes.
The main structural change was to put back the time argument passed to VODE's rhs function.
Although our networks are not explicitly time dependent, this is essential for generality to time dependent rhs in more general applications. So I thought it would be best to preserve what time arguments are passed in what parts of VODE in the C++ version.
> Fixes some minor issues in vode-cxx before merging to development

- networks/general_null/network_header.template
- networks/general_null/write_network.py
This adds an enum like
```
namespace Species {
enum NetworkSpecies {
He4=1,
C12,
O16,
Ne20,
Mg24,
Si28,
S32,
Ar36,
Ca40,
Ti44,
Cr48,
Fe52,
Ni56,
NumberSpecies=Ni56
};
};
```
to the `network_properties.H` file.
To test this, in `test_react` (or any unit test), do:
```
make net_prop_debug
```
and then look in `tmp_build_dir` for the `network_properties.H`
> add a species name enum to network_properties.H

- networks/aprox13/Make.package
- networks/aprox13/actual_network.H
- networks/aprox13/actual_network_data.cpp
- networks/aprox13/actual_rhs.H
- networks/aprox13/actual_rhs_data.cpp
- unit_test/test_rhs/inputs_aprox13
- unit_test/test_rhs/probin.aprox13
- util/esum.H
- util/esum_cxx.py
This PR ports aprox13 to C++ using the same strategy as for iso7 in #303 
Here are the fcompare results between C++ and Fortran for the `test_rhs` unit test:
[fc_aprox13_rhs.txt](https://github.com/starkiller-astro/Microphysics/files/4484423/fc_aprox13_rhs.txt)
Here are the fcompare results between C++ and Fortran for the `test_react` unit test:
[fc_aprox13_react.txt](https://github.com/starkiller-astro/Microphysics/files/4484426/fc_aprox13_react.txt)
This PR also adds input files for `test_rhs` for aprox13 based on test_react inputs, except I've added `call_eos_in_rhs=T`.
To avoid completely refactoring the rhs in aprox13, I also enabled passing arbitrary size `Array1D` arrays to all esum functions by making esums templated functions.
I've also run the `test_rhs` and `test_react` unit …
> Move aprox13 to C++

- integration/VODE/_parameters
- integration/VODE/vode_integrator_simplified_sdc.F90
- interfaces/sdc_type.F90
This PR adds the number of total SDC iterations to the `sdc_t` derived type for simplified SDC and adds an extern parameter `sdc_burn_tol_factor` for VODE (defaulted to 1.0 for no effect).
If the user wishes to adjust the ODE tolerances with the SDC iteration number, `sdc_burn_tol_factor` is accounted for in VODE for simplified SDC as follows:
```
sdc_tol_fac = sdc_burn_tol_factor**(state_in % num_sdc_iters - state_in % sdc_iter - 1)
```
Then the integrator absolute and relative tolerances are scaled by `sdc_tol_fac`.
> Modify simplified SDC tolerances with SDC iteration number

- integration/VODE/vode_integrator_simplified_sdc.F90
This PR implements the changes described in #310 for `SDC_EVOLVE_ENERGY` and `SDC_EVOLVE_ENTHALPY` for the simplified SDC burning mode.
Absolute tolerances for `rho*X`, `rho*E`, or `rho*h` are set to the absolute tolerances in the inputs file for species and enuc, respectively, scaled by density `rho_min`.
The density scale `rho_min` is:
`rho_min = min(rho(0), rho(0) + rho_advective_source * dt)`
For `SDC_EVOLVE_ENERGY`, `rho_advective_source` is the density advective source in the `sdc_t` passed to the integrator.
For `SDC_EVOLVE_ENTHALPY`, `rho_advective_source` is the sum of the advective sources for the partial densities `rho * Xi` for the species.
> For simplified SDC, scale the absolute tolerances by density

- conductivity/stellar/actual_conductivity.H
The stellar conductivity `actual_conductivity.H` header file needs a `using namespace amrex` statement so that the compiler can resolve the `Real` variable types.
> Add amrex namespace to stellar conductivity header

- conductivity/constant/actual_conductivity.H
- conductivity/constant_opacity/actual_conductivity.H
- conductivity/powerlaw/actual_conductivity.H
The `actual_conductivity.H` header files use variables defined in `extern_parameters.H`, so this file should be `#include`d so that successful compilation does not require the files to be `#include`d in a specific order.
> Include extern_parameters.H in actual_conductivity headers

- integration/VODE/vode_type_simplified_sdc.F90
- interfaces/burn_type.F90
This PR fixes some compilation errors when using SDC_EVOLVE_ENTHALPY, which is used by MAESTROeX.
> Fix to compile with MAESTROeX SDC

- rates/aprox_rates.H
- rates/aprox_rates_data.H
- rates/aprox_rates_data.cpp
I think the Langanke implementation in C++ wasn't quite right due to possible off-by-one indexing errors in the arrays as they were converted from 1-indexing to 0-indexing. Rather than sort it out, I just replaced GpuArrays with Array1D and used 1-indexing everywhere, and this now matches the Fortran output for aprox21 for the rates that depend on it (e.g. d(Cr56)/dt).
> Fix indexing errors in Langanke C++ implementation

- rates/aprox_rates.H
Although in the long term it would be good to sync up mathematical and physical constants with more accurate values, our immediate concern is making the C++ port match the Fortran code, and restoring the approximate value of pi hardcoded in the Fortran is necessary to do that (otherwise we get differences at the 1e-9 level for the rates depending on the output of ecapnuc, such as jac(He3, H1)).
> Restore approximate value of pi in ecapnuc

- integration/VODE/vode_type_simplified_sdc.F90
The bit at the end of this routine that did the actual Jacobian conversion used `k` as a loop index and this was actually being treated as the `K` that was used to measure kinetic energy (since Fortran is case insensitive).
> Fix indexing that accidentally used a real as an int

- CHANGES.md
- integration/VODE/vode_dvstep.H
- integration/VODE/vode_integrator.H
- integration/VODE/vode_type.H
Commit 9d3ddb13b8abf8953756ef6dc036ed569d27664b added intentional failure modes to the VODE integrator to prevent VODE from giving us a state where the integrator believed it was successful but the state was not physically valid. Specifically, we checked on T < 0 and X < -0.01 or X > 1.01. Although this gave us the opportunity to then retry the burn, retries are expensive and we'd like to avoid them if possible (#106). One way we can significantly mitigate this is by preventing these failure modes from occurring at the end of each step rather than only at the end of the burn. We can then rely on the integrator's built-in step retry mechanism (which decreases dt or changes the integration order).
I chose to use the same failure modes as the one at the end of the burn. Additionally, I added …
> VODE steps fail if the state is not valid

- Make.Microphysics
- networks/aprox13/test-cpp/GNUmakefile
- networks/aprox13/test-cpp/Make.package
- networks/aprox13/test-cpp/do_initialization.f90
- networks/aprox13/test-cpp/main.cpp
- networks/aprox13/test-cpp/testburn.f90
- networks/aprox13/test-cpp/testjacobian.f90
- networks/aprox19/test-cpp/GNUmakefile
- networks/aprox19/test-cpp/Make.package
- networks/aprox19/test-cpp/do_initialization.f90
- networks/aprox19/test-cpp/main.cpp
- networks/aprox19/test-cpp/testburn.f90
- networks/aprox19/test-cpp/testjacobian.f90
- networks/aprox21/test-cpp/GNUmakefile
- networks/aprox21/test-cpp/Make.package
- networks/aprox21/test-cpp/do_initialization.f90
- networks/aprox21/test-cpp/main.cpp
- networks/aprox21/test-cpp/testburn.f90
- networks/aprox21/test-cpp/testjacobian.f90
- networks/iso7/Make.package
- networks/iso7/test-cpp/GNUmakefile
- networks/iso7/test-cpp/Make.package
- networks/iso7/test-cpp/do_initialization.f90
- networks/iso7/test-cpp/main.cpp
- networks/iso7/test-cpp/testburn.f90
- networks/iso7/test-cpp/testjacobian.f90
A lot of networks have a test-cpp/ subdirectory that just exercises the RHS for that network.  This gets some of these building again, and removes all the dependencies on Castro.
> get some of the scattered unit tests building again

- interfaces/network.H
- networks/general_null/network_header.template
The static variables in `network_properties.H` are warned as unused with GCC everywhere we include the header and don't use them all.  This uses the `[[gnu::unused]]` attribute to silence these warnings.
> Warning fixes

- interfaces/burn_type.H
- interfaces/eos_type.H
- unit_test/eos_cell/GNUmakefile
- unit_test/eos_cell/Make.package
- unit_test/eos_cell/_parameters
- unit_test/eos_cell/eos_cell.H
- unit_test/eos_cell/eos_cell_F.H
- unit_test/eos_cell/inputs_eos
- unit_test/eos_cell/main.cpp
- unit_test/eos_cell/probin
- unit_test/eos_cell/unit_test.F90
This adds the eos_cell unit test which simply calls the (C++) EOS on a single zone and outputs the information.  To do the output, this creates a << operator for an eos_t.  We also fix a bug in the burn_t << for aux data.
closes #174
> create a routine to call any of the EOSes with a single thermodynamics state

- integration/VODE/vode_rhs.H
> remove the burn_to_vode in jac() -- it appears unnecessary

- integration/BS/bs_integrator.F90
- integration/BS/bs_rpar.F90
- integration/BS/bs_type.F90
- integration/CVODE/cvode_rhs.F90
- integration/CVODE/cvode_rpar.F90
- integration/CVODE/cvode_type.F90
- integration/VODE/vode_integrator.F90
- integration/VODE/vode_rhs.F90
- integration/VODE/vode_rpar.F90
- integration/VODE/vode_type.F90
- interfaces/burn_type.F90
- interfaces/burn_type.H
these (cs, dx, t_sound) were all used for the different burning modes
> remove some unused parameters

- networks/aprox13/actual_rhs.H
- networks/aprox19/actual_rhs.H
- networks/ignition_simple/actual_rhs.H
- networks/iso7/actual_rhs.H
- networks/rate_type.H
- networks/triple_alpha_plus_cago/actual_rhs.H
In every place in the networks where we are using rate_t, it works just as well to have an array of rate_t, where the size of the array is the number of rate groups, as it does to have the rate_t be a 2D array. Making this change has two benefits: we can clean up some of the RHS code later, because the RHS (unlike the Jacobian) typically does not actually need to fill all the rate groups (so this will save work and memory), and also this will support the change in #413.
> Remove array over NumGroups from rate_t

- interfaces/network_initialization.cpp
We pull in this file if USE_CXX_REACTIONS = TRUE, but if that is set without USE_REACT = TRUE, we will attempt to pull in actual_network.H, which only exists for some networks.
> Guard against pulling in actual_network

- CHANGES.md
- integration/VODE/vode_rhs.H
- integration/VODE/vode_rhs_simplified_sdc.H
- integration/VODE/vode_type_simplified_sdc.H
- interfaces/Make.package
- interfaces/fortran_to_cxx_actual_rhs.F90
- interfaces/fortran_to_cxx_actual_rhs.H
- interfaces/network_initialization.cpp
- networks/aprox13/Make.package
- networks/aprox19/Make.package
- networks/ignition_simple/Make.package
- networks/iso7/Make.package
- networks/powerlaw/Make.package
- networks/triple_alpha_plus_cago/Make.package
- unit_test/test_rhs/rhs_zones.H
If a network has a C++ RHS implementation, it should set `DEFINES += -DNETWORK_HAS_CXX_IMPLEMENTATION` in its Make.package, and the C++ integrator will continue to use it. Otherwise, we default to the Fortran RHS, and we add a wrapper script that translates between the C++ RHS/Jac and the Fortran RHS/Jac.
With this change, any downstream application can use `USE_CXX_REACTIONS = TRUE` everywhere and still use any network. The only catch is that there is no CUDA implementation right now in this PR, so the legacy Fortran networks won't run on GPUs. If we need to fix that later, it should be possible.
> Add interface for C++ integrator to use Fortran RHS

- integration/BS/Make.package
- integration/CVODE/Make.package
- integration/VODE/Make.package
- integration/integrator.F90
In this case, we just make integrator.F90 a no-op.
> Allow integrator to have only a C++ implementation

- integration/VODE/Make.package
- integration/VODE/actual_integrator.H
- integration/VODE/actual_integrator_simplified_sdc.H
- integration/integrator.H
- integration/integrator_sdc.H
This syncs up with the Fortran scheme where (at least for now) we'll have exactly one actual_integrator.H per build, which allows us to easily swap them out when we add others.
> Allow other C++ integrators

- networks/aprox19/nse.H
now we can pass in an eos_t or a burn_t
> make in_nse a templated function

- unit_test/test_sdc/inputs_aprox19.no_nse
- unit_test/test_sdc/probin.aprox19.no_nse
this disables calling the NSE table, but will do the thermodyanics via aux
> add inputs that can test the SDC code path with USE_NSE

- EOS/Make.package
- EOS/breakout/Make.package
- EOS/gamma_law/Make.package
- EOS/gamma_law_general/Make.package
- EOS/helmholtz/Make.package
- EOS/multigamma/Make.package
- EOS/polytrope/Make.package
- EOS/rad_power_law/Make.package
- EOS/stellarcollapse/Make.package
- EOS/ztwd/Make.package
- Make.Microphysics_extern
- interfaces/Make.package
- interfaces/microphysics.F90
- unit_test/test_eos/Make.package
- unit_test/test_eos/main.cpp
- unit_test/test_eos/test_eos_F.H
- unit_test/test_eos/unit_test.f90
By default, we set `USE_FORT_EOS ?= TRUE` in the `Make.Microphysics_extern`, so no codes will need to be changed.
This addresses part of #453
> allow the EOS to be turned off by setting USE_FORT_EOS=FALSE

- interfaces/eos.H
- unit_test/burn_cell/main.cpp
- unit_test/eos_cell/main.cpp
- unit_test/test_aprox_rates/main.cpp
- unit_test/test_conductivity/main.cpp
- unit_test/test_eos/main.cpp
- unit_test/test_react/main.cpp
- unit_test/test_rhs/main.cpp
- unit_test/test_screening/main.cpp
- unit_test/test_sdc/main.cpp
This is needed because the downstream codes do not make these variables available as globals without a namespace.
> Pass small_temp and small_dens into eos_init

- unit_test/test_react/probin.iso7
In #457 we discovered that rearranging some iso7 Jacobian terms can unintentionally make the analytic Jacobian worse. Unfortunately there is not much we can do about that without some larger changes to our Jacobian strategy, such as perhaps attempting to capture the effects of screening. For now we do not really have a choice but to work around the problem by keeping the integration time relatively short so that it completes in a semi-reasonable amount of time.
> Shorten iso7 integration time

- integration/ExplicitAsymptotic/Make.package
- integration/ExplicitAsymptotic/README.md
- integration/ExplicitAsymptotic/_parameters
- integration/ExplicitAsymptotic/actual_integrator.H
The explicit integration method of [Guidry et al. (2013)](https://ui.adsabs.harvard.edu/abs/2013CS%26D....6a5001G/abstract) (paper 1 of 3) is implemented. In this approach we detect which terms in the species RHS would equilibrate within the current integration timestep and then use the asymptotic approximation to update that term instead of normal explicit integration.
This seems to work OK for "easy" burns at low temperature -- the answer is fairly inaccurate for the default choice of parameters, presumably due to the first order method, but if we are very restrictive on the timestep then the answer converges to what VODE provides. Near NSE we just run into the same problems as the simple forward Euler integrator, which will require the "partial equilibrium" method that detects which …
> Add explicit integrator with asymptotic approximation

- unit_test/test_rhs/inputs_iso7
- unit_test/test_rhs/probin.iso7
Since we're just evaluating the RHS we can afford to do it over more zones and still have the test complete within a few seconds. Also, since the critical piece of this network is the silicon burning, I made that one of the primary species.
> Test iso7 RHS more comprehensively

- EOS/breakout/actual_eos.H
- EOS/gamma_law/actual_eos.H
- EOS/gamma_law_general/actual_eos.H
- EOS/helmholtz/actual_eos.H
- EOS/multigamma/actual_eos.H
- EOS/polytrope/actual_eos.H
- EOS/rad_power_law/actual_eos.H
- EOS/ztwd/actual_eos.H
- interfaces/eos.H
This will be necessary for some compile-time evaluation we want to do for #470.
> Template on eos_input_t

- interfaces/eos_type.H
To do #470 we will need to be able to determine at compile time if a given template type has certain member data. This adds a few structs for that purpose. The idea is that they can be used like
```
if constexpr (has_xne_xnp<T>::value) {
state.xne = xnefer;
state.xnp = 0.0e0_rt;
}
```
The intended usage above requires C++17, but this PR does not yet require that.
> Add types to determine if an EOS type has given members

- integration/QSS/_parameters
- integration/QSS/actual_integrator.H
* Initialize n_rhs to 0
* If any X goes sufficiently negative or > 1, reject the timestep immediately and cut by a factor of 2
* Fix predictor for e
* The predictor needs to be evaluated inside the timestep loop, not before it, since it depends on dt
> Various improvements to the QSS integrator

- EOS/breakout/actual_eos.H
- EOS/gamma_law/actual_eos.H
- EOS/gamma_law_general/actual_eos.H
- EOS/helmholtz/actual_eos.H
- EOS/multigamma/actual_eos.H
- EOS/polytrope/actual_eos.H
- EOS/rad_power_law/actual_eos.H
- EOS/ztwd/actual_eos.H
- integration/VODE/cuVODE/test/main.cpp
- interfaces/eos.H
- interfaces/eos_type.H
- unit_test/test_aprox_rates/main.cpp
- unit_test/test_conductivity/main.cpp
- unit_test/test_eos/main.cpp
- unit_test/test_react/main.cpp
- unit_test/test_rhs/main.cpp
- unit_test/test_screening/main.cpp
- unit_test/test_sdc/main.cpp
- util/build_scripts/write_probin.py
- Use of single argument static_assert without a message is C++17-only
- One usage of static_assert in helmeos was prematurely implemented at compile time instead of runtime
- Shadowing of small_dens and small_temp in eos.H
- Unknown compiler pragmas (pragma gpu)
- Invalid use of compound literals in eos_type.H (C99 only)
- slen is unused in extern_parameters.cpp if there are no string parameters
> Address various compiler warnings

- interfaces/eos.H
This fixes an issue in #495 that was avoiding some global variable shadowing, but didn't change all the variable names correctly.
> Fix variable names in eos_init

- interfaces/eos.H
This is a first demonstration of how we can use C++17 `if constexpr` to template out unnecessary logic.
> Skip EOS reset if eos_t doesn't have relevant quantities

- EOS/helmholtz/actual_eos.H
Continues #470 by compiling out accesses to members of the struct sent to the EOS that are invalid. This will allow us later to, for example, send a type to the EOS that doesn't have entropy or enthalpy.
We don't explicitly compile out all intermediate expressions that led up to the quantities in question. That could be done, but compilers should be able to recognize that as dead code and compile it out for us.
> Only access variables in the state in Helmholtz

- util/build_scripts/runtime_parameters.py
- util/build_scripts/write_probin.py
now the Fortran "get" routines are part of runtime_parameters.py.  This also adds array support.  This will help with porting the Castro problem parameters over.
> move more stuff into the build scripts

- util/linpack.H
`RArray1D` and `RArray2D` are one-based arrays, and that causes friction with the zero-based indexing of `xn` and other arrays. So we want to move everything to zero-based indexing.
The strategy will be to suffix function parameters with "1", e.g. `a` -> `a1`, and then do
```
auto& a = reinterpret_cast<Array2D<Real, 0, num_eqs-1, 0, num_eqs-1>&>(a1)
```
Then, in the function, we can convert all the calculations to zero-based indexing. When all of the conversions have been done, we can do one final sweep to convert `RArray1D` and `RArray2D` to be zero-based and then remove all the `reinterpret_cast` statements and rename the function parameters to their original names. This will allow us to do an incremental conversion.
> Start moving towards zero-based indexing with linpack

- networks/rprox/Make.package
- networks/rprox/actual_rhs.H
rprox was not actually using the C++ implementaiton.  This fixes that and fixes compilation.  This now runs on the GPU.
> fix rprox GPU / C++

- README.md
it is no longer travis, but now a github action
> fix the docs building badge

- networks/aprox13/actual_network.H
- networks/aprox13/actual_network_data.cpp
- networks/aprox13/actual_rhs.H
This change folds the reaction pairs (irmgap, irr1), which did Mg24 -> Al27 -> Si28, and (irsigp, irr1), which did Si28 -> Al27 -> Mg24, into the effective Mg24 <-> Si28 rates. This allows us to remove irr1 from the rate list. More importantly it works toward the goal where every "reaction" known to the network connects an actual pair of species in the network, while any intermediate rates connecting the two can be considered implementation details, which will be helpful for methods looking at microscopic equilibria. This change will be followed by removing the rest of the intermediate proton links.
> aprox13 3/∞

- networks/aprox13/actual_rhs.H
Calculate density dependence in tabulated rates inline. This will help in a future step where we can query `aprox13tab` a rate at a time instead of computing all the (unscreened) rates at once.
> aprox13 4/∞

- integration/utils/jacobian_utilities.H
This will need to be replaced later with a correct solution for integrating enthalpy
> Remove constant pressure burn code path in C++

- integration/ForwardEuler/actual_integrator.H
- integration/QSS/actual_integrator.H
- integration/VODE/vode_type_strang.H
- integration/_parameters
For now, this is done for Strang only.
Note: in principle this could break a setup that was previously explicitly setting `call_eos_in_rhs = F`. However, I think this is pretty unlikely to have happened, I only found one setup (Castro xrb_mixed) that is doing it.
> Re-enable call_eos_in_rhs option

- networks/aprox13/actual_network.H
- networks/aprox13/actual_network_data.cpp
- networks/aprox13/actual_rhs.H
- networks/aprox19/actual_network.H
- networks/aprox19/actual_network_data.cpp
- networks/aprox19/actual_rhs.H
- networks/aprox19/nse.H
- networks/aprox21/actual_network.H
- networks/aprox21/actual_network_data.cpp
- networks/aprox21/actual_rhs.H
- networks/ignition_simple/actual_network.H
- networks/ignition_simple/actual_network_data.cpp
- networks/ignition_simple/actual_rhs.H
- networks/iso7/actual_network.H
- networks/iso7/actual_network_data.cpp
- networks/iso7/actual_rhs.H
- networks/rprox/actual_network.H
- networks/rprox/actual_network_data.cpp
- networks/rprox/actual_rhs.H
- networks/triple_alpha_plus_cago/actual_network.H
- networks/triple_alpha_plus_cago/actual_network_data.cpp
- networks/triple_alpha_plus_cago/actual_rhs.H
This will be helpful later for building a generic energy RHS function that just assumes the network supplies mion, so we can reduce redundancy.
> Move mion and bion to generic network namespace

- interfaces/burner.H
Make sure that `sdc_nse_burn` is called if using simplified SDC
> Fix call to nse_burn for SDC

- integration/VODE/actual_integrator_simplified_sdc.H
it should be left unscaled.  only atol gets scaled by rho
> fix scaling of rtol for species in SDC

- networks/aprox19/nse.H
We now do the NSE SDC update by iteratively constructing the source terms to the aux data.  This no longer requires the lagged source terms from the previous iteration and seems to converge better than what we were doing.
> change the NSE-SDC update

- integration/ForwardEuler/actual_integrator.H
- integration/QSS/actual_integrator.H
- integration/VODE/vode_type_simplified_sdc.H
- integration/VODE/vode_type_strang.H
- interfaces/burn_type.H
this can be used to recover from failed burns, e.g., the NSE bailout
> store the integration time achieved in the burn_t

- integration/VODE/actual_integrator.H
- integration/VODE/actual_integrator_simplified_sdc.H
- integration/VODE/vode_dvode.H
- interfaces/burner.H
this changes the behavor of VODE to detect if we hit NSE during
the course of integration, and if so, we return a new error code
and we will catch that and finish the burn via NSE
> bail out of integration if we hit NSE

- integration/VODE/vode_jac_util_simplified_sdc.cpp
- integration/VODE/vode_rhs_simplified_sdc.H
the numerical Jacobian is already in terms of X, so we were doing unnecessary
scalings by aion
> for jacobian == 3, we don't need to scale by aion

- opacity/rad_power_law/actual_opacity.H
- opacity/rad_power_law/opacity_table_module.F90
In Castro originally the floor on kappa was only applied to the Rosseland opacity for numerical stability reasons. This change reverts to that previous behavior. This error in the port explains AMReX-Astro/Castro#1539; in that problem setup we had kappa_floor = 1.e-5, which is larger than the actual constant kappa for the Planck mean. We could still have separate floors for kappa_r and kappa_p but that would be done in a separate change.
> kappa_floor should only be applied to Rosseland opacity

- integration/VODE/vode_rhs.H
update_thermodynamics already ensures that the burn_t is valid, so we don't need a vode_to_burn (or later burn_to_vode) call in vode_rhs.
> remove some unnecessary calls in Strang

- interfaces/network_utilities.H
- networks/iso7/actual_network.H
- networks/iso7/actual_rhs.H
Now that #567 is done, we can remove the custom infrastructure for the Jacobian. Now in iso7, both the RHS and the Jacobian are automatically constructed from a single source of truth in actual_network.H.
> Remove Jacobian infrastructure for d(rate)/dY

- unit_test/test_aprox_rates/GNUmakefile
- unit_test/test_aprox_rates/aprox_rates_util.cpp
- unit_test/test_aprox_rates/main.cpp
- unit_test/test_aprox_rates/test_aprox_rates.H
> since we've merged the c12ag rates, modify the test_aprox_rates function calls

- integration/VODE/actual_integrator_simplified_sdc.H
if we bailout after the first step, then t = 0 and we generate
an Inf if we try to compate an energy generation rate.  Now we
protect against this.
> fix the case of an immediate NSE bailout

- integration/VODE/actual_integrator_simplified_sdc.H
- integration/VODE/vode_dvode.H
- integration/VODE/vode_type.H
VODE sometimes does some initial exploration that is rejected, but may
trigger the NSE bailout, resulting in a very bad state with huge NSE
energy release.  Now we instead don't check for the NSE bailout until after
10 steps have been taken.  The number 10 is arbitrary, but seems sufficient
for VODE to have settled down.
> only check for NSE bailout after 10 steps

- integration/utils/numerical_jacobian.H
this should not be needed, but some times VODE explores things early on
and bad things can happen.
> add a check on the perturbed T in the numerical Jacobian

- interfaces/eos_type.H
This templates the `<<` operator for the structs in `eos_type.H`, adding checks to see whether variables exist in the struct so it should now work for any of the eos structs defined in that file.
This addresses #629.
> Template the eos_type output operator

- unit_test/burn_cell_sdc/inputs_subch2_failure_stepreject
if we uncomment out the logic in vode_dvstep.H that rejects a step if
the change in a species from one step to the next is too large, then
this inputs fails.
> add inputs that causes SDC integration fail with step rejection

- integration/VODE/vode_dvstep.H
we were storing it in the step trial loop, which meant if there
were successive failures, then we would use the old failed state
as the reference to check the increase in species against.  This
make the species step rejection stuff not work reliably.
This also changes SDC to limit based on X instead of rho X
> store y_save before attempting any steps

- Make.Microphysics
- Make.Microphysics_extern
- unit_test/test_jac/GNUmakefile
- unit_test/test_react/GNUmakefile
- unit_test/test_rhs/GNUmakefile
- unit_test/test_sdc_vode_rhs/GNUmakefile
this now cleans up the pynucastro files and helm in the _extern stub
this way application codes pick up these rules automagically
> do a better job at cleaning up linked files

- networks/aprox19/actual_rhs.H
- networks/aprox21/actual_rhs.H
In both aprox19 and aprox21 there is the reaction sequence Fe52(a,p)Co55(p,g)Ni56. Co55 is an equilibrium isotope in this reaction chain, and its equilibrium abundance depends on both this reaction sequence as well as the reaction Fe54(p,g)Co55. Since there are two contributions to the effective y(Co55), the rate ends up being somewhat complicated, but the RHS term ends up simply looking like `y(Fe52) * y(He4) * y(P) * rate`. The Jacobian terms consequently have a d/dP entry. However, although the proton abundance plays a role in determining the rate, the reaction sequence doesn't actually consume or produce a net proton, so it is more appropriate to think of y(P) as being part of the rate rather than part of the RHS. If the y(P) is absorbed into the rate, then this term should not appear …
> Remove implicit d/dP terms in aprox19 and aprox21 Jacobians

- interfaces/burn_type.F90
- interfaces/network.F90
- networks/Make.package
this still allows us to query species properties from Fortran
this is needed by initial_models for now
> fix the network Fortran module

- interfaces/eos_type.H
This fixes #859.
Note that I think this can be done more elegantly by [matching all structs which inherit from eos_base_t](https://en.cppreference.com/w/cpp/types/is_base_of), so that could be a future improvement.
> Template EOS operator<< and use SFINAE to only operate on eos_t

- integration/VODE/vode_rhs_simplified_sdc.H
- integration/VODE/vode_type_simplified_sdc.H
- sphinx_docs/source/eos.rst
since we have shifted such that the SDC VODE state is in the same
order as Strang, we no longer need a temporary.  This frees up
memory and a potentially expensive copy.
This can give roundoff diffs
> for simplified-SDC, eliminate a temporary ydot_react array

- integration/_parameters
- python_library/StarKiller/StarKiller/examples/BurnProfile/probin_aprox21
- python_library/StarKiller/StarKiller/examples/rotating_star/probin_aprox21
- unit_test/test_react/inputs_3alpha
- unit_test/test_react/inputs_reaclib_cburn
- unit_test/test_react/inputs_reaclib_ctest
- unit_test/test_react/inputs_reaclib_urca
- unit_test/test_react/old/inputs_reaclib_cburn.128
- unit_test/test_react/old/inputs_reaclib_cburn.32
- unit_test/test_react/old/inputs_reaclib_cburn.64
- unit_test/test_react/old/inputs_reaclib_urca.32
- unit_test/test_react/old/inputs_reaclib_urca.64
the code that implemented this was removed a long time ago.
This just removes the parameter.
> retry_burn is no longer supported

- integration/VODE/vode_rhs_simplified_sdc.H
- integration/utils/numerical_jacobian.H
this removes an unneeded EOS call as well as eliminates a copy
(this will close #897)
> clean up the simplified SDC numerical Jacobian a bit

- networks/general_null/network_header.template
- rates/aprox_rates.H
This seems to work for `castro/Exec/hydro_tests/Sod` with rocm 5.1.0
Most other places in the code Array1D is used for any quantities accessed inside the kernels, however this would require more intrusive changes to the code which uses these constants.
> Change aion, aion_inv, and zion to have constexpr

- unit_test/test_rhs/main.cpp
the idea of this test is to directly call the network's RHS functions,
so we only want to test the Jacobian that the network implements
> test_rhs only makes sense with jacobian = 1

- screening/screen.H
This just adds template parameters to the individual methods and wrappers that disable the T derivatives if we're doing a numerical Jacobian.
> Start templating out T derivatives in screening

- nse/nse_index.cpp
To fix the issue where nse indices are initialized to 0, which causes an issue when the network does not have photoionization proton. All indices are now initialized to -1 to prevent this issue.
> nse indices fix

- integration/ForwardEuler/actual_integrator.H
- integration/VODE/actual_integrator.H
- integration/VODE/actual_integrator_simplified_sdc.H
- interfaces/burn_type.H
- unit_test/test_react/main.cpp
- unit_test/test_react/react_zones.H
this is a better metric than the number of RHS calls when comparing different Jacobians.
test_react now outputs a summary as well.  Note that the sum() we were doing there was local, so it would not have worked with MPI.  This is now fixed.
> add the number of steps taken to the burn_t

- nse/_parameters
- nse/actual_nse.H
- nse/make_table/burn_cell.H
- unit_test/test_nse/GNUmakefile
- unit_test/test_nse/_parameters
- unit_test/test_nse/inputs_aprox13
- unit_test/test_nse/inputs_aprox19
- unit_test/test_nse/inputs_aprox21
- unit_test/test_nse/inputs_iso7
- unit_test/test_nse/inputs_subch2
- unit_test/test_nse/nse_example.H
Done:
1) Tried to update n_e while doing iterations, but it turns out it doesn't improve convergence and can make it worse. So I discarded that idea.
2) Since scipy.fsolve also returns incorrect solutions with no errors were raised,  I guess it is how hybrj is supposed to work.
3) Added convergence check for hybrj
4) I think mode 1 works better actually? So I changed it back to mode 1...
5) Transplant the fine-tuning of initial guess procedure in pynucastro for scipy.fsolve to hybrj solver, making it more robust at solving nse.
6) change criteria for making the table of solving initial guesses. With fine-tuning, it is easier to solve them.
7) modify nr procedure to use constraint equations for hybrj (although it is almost never a case we should use nr over hybrj, especially with the …
> improve and clean up nse solver

- integration/VODE/_parameters
- integration/VODE/vode_type_simplified_sdc.H
- integration/VODE/vode_type_strang.H
currently for both Strang and simplfiied-SDC integration, we clip the species in clean_state to lie in [0, 1].  But we already have step rejection logic that enforces this, and some testing shows that this clipping makes VODE work a lot harder.
> add the option to disable clipping species

- CHANGES.md
- Make.Microphysics_extern
- screening/screen.H
- sphinx_docs/source/screening.rst
Selected by `SCREEN_METHOD=null`, closes #984
> Add a null screening routine

- integration/QSS/actual_integrator.H
This synchronizes QSS with the other integrators and the applications.
> Subtract off initial energy at end of QSS integration

- networks/rhs.H
This simply ensures that for d(f(Y_1)) / dY_2, Y_1 is actually present in a given RHS term. This is a redundant check for now which can give us some freedom later.
> Add a safeguard to jac_term

- Make.Microphysics_extern
- nse_solver/nse_solver.H
we need to inline the functions so the compiler doesn't complain about multiple versions.  Also add a check that we are not trying to do both kinds of NSE.
> fix self-consistent NSE compilation

- integration/integrator_type_strang.H
- integration/nse_update.H
- interfaces/burn_type.H
- nse_solver/nse_solver.H
- unit_test/burn_cell/burn_cell.H
- unit_test/test_react/react_zones.H
we were not being consistent with how we handled T_fixed, which is set if we are doing drive_initial_convection (Castro Strang update coming soon).  The idea is that the zone's internal energy should not be computed off of T_fixed, but all of the reaction rates should be.  This update fixes some issues with NSE and Strang burning where were we computing e with T_fixed, thus changing the amount of internal energy in a zone.
> swtich Strang over to use T_fixed + update SDC + NSE

- nse_solver/nse_solver.H
the state was undefined and causing valgrind errors
> initial h1_index mass fraction in nse_solver

- networks/aprox19/actual_network.H
- networks/aprox19/actual_network_data.cpp
- networks/aprox19/nse_table.H
- networks/aprox21/actual_network.H
- sphinx_docs/source/nse.rst
there is now a table_idx() function that can be used to get the correct index into the 1-d table.
this makes new constexpr for the table deltas
eliminates arrays to store T, rho, ye at the table points, since those are easily computed
replaces some magic numbers with more consts
> some cleaning for the NSE table

- nse_solver/nse_check.H
add composition() to find abar and zbar.
> fix uninitialized variable for nse

- networks/rhs.H
Fixes uninitialized memory errors in aprox19 and aprox21 introduced by #1054.
> Explicitly initialize rates to 0 in tabulate_rates

- screening/screen.H
My testing with autodiff found a couple mistakes in the analytic derivatives for the chabrier1998 screening. Also fixed some compiler warnings in chugunov2007 and chugunov2009.
> Fixes to screening routines

- Make.Microphysics_extern
- nse_solver/_parameters
- nse_solver/nse_check.H
- sphinx_docs/source/nse.rst
add an option to ignore the check where we want the time scale of the rates to be smaller than the sound crossing time scale.
> add an option to ignore checking the timescale of the rate for NSE_NET

- CHANGES.md
- Make.Microphysics_extern
- nse_solver/_parameters
- nse_solver/nse_check.H
Since forward and reverse rates depend on the mass fractions, to do a more cruel estimation, we can use nse mass fractions instead. This way, the thermodynamic condition becomes the only deciding factor.
Note here we still need to make sure the current mass fractions are not terribly away from the nse mass fractions, so only allow it after the first check, which checks on whether the current mass fractions are close to the nse mass fractions.
> add another option to use nse mass fractions for NSE_NET check

- Make.Microphysics
- util/build_scripts/write_probin.py
This fixes cache misses when using ccache and a race condition that was causing intermittent CI failures
> Make sure generated code is identical between make runs and fix CI failure

- CMakeLists.txt
Following from #1056 we now use namespaces in CMake build for Microphysics.
The primordial chem test passes for me both with and without CMake.
> Using namespaces in CMake

- networks/primordial_chem/_parameters
- networks/primordial_chem/actual_rhs.H
- unit_test/burn_cell_primordial_chem/burn_cell.H
- unit_test/burn_cell_primordial_chem/inputs_primordial_chem
We have to assume a certain redshift for doing Pop III simulations with primordial chemistry. We use z = 30, but it is also common to use a value between z = 20-30. With this PR, the user can define the redshift they want as a runtime parameter.
@zingale - I don't think Microphysics already has a redshift parameter embedded somewhere, right?
> Use redshift as a runtime parameter in primordial chem

- util/build_scripts/write_probin.py
Sort the runtime parameter namespaces in `extern_parameters.H` and `extern_parameters.cpp`.
> Fix ccache misses due to generated files

- integration/VODE/actual_integrator.H
- integration/VODE/actual_integrator_simplified_sdc.H
- integration/VODE/vode_dvhin.H
- integration/VODE/vode_dvjac.H
- integration/VODE/vode_dvjust.H
- integration/VODE/vode_dvnlsd.H
- integration/VODE/vode_dvode.H
- integration/VODE/vode_dvset.H
- integration/VODE/vode_dvstep.H
- integration/VODE/vode_type.H
- integration/integrator_data.H
With this change, the number of equations integrated by VODE is now counted from the components of the burn_t, rather than being hardcoded at compile time (at least for Strang; SDC will be handled in a future change). This sets up a possible future change where different burn state objects are passed to the integrator at different times. The motivating use case is Quokka's desire to integrate (xn, e) at some times and (e_gas, e_radiation) at other times. A future change could support the integration of an object other than burn_t, particularly an object that does not have xn but has (multigroup) radiation energy, as long as the integration tolerances (and any other auxiliary information) are made consistent.
> Template VODE on number of integrator equations

- integration/integrator_rhs_simplified_sdc.H
- integration/integrator_type.H
- integration/integrator_type_simplified_sdc.H
> update the interface for update_density_in_time

- integration/BackwardEuler/actual_integrator_simplified_sdc.H
- integration/RKC/actual_integrator_simplified_sdc.H
- integration/VODE/actual_integrator_simplified_sdc.H
basically, once we convert back from the integrator type to the burn_t, we should not have to use the integrator type any more.  This will make it easier to merge these code paths in the future.
> simplify some logic in the SDC integrators

- integration/BackwardEuler/actual_integrator.H
- integration/BackwardEuler/actual_integrator_simplified_sdc.H
- integration/ForwardEuler/actual_integrator.H
- integration/QSS/actual_integrator.H
- integration/RKC/actual_integrator.H
- integration/RKC/actual_integrator_simplified_sdc.H
- integration/VODE/actual_integrator.H
- integration/VODE/actual_integrator_simplified_sdc.H
- interfaces/burn_type.H
this will allow the application code to be more descriptive about failures
> store the error code returned by the integrator in burn_t

- interfaces/network_initialization.cpp
- networks/aprox13/actual_network.H
- networks/aprox13/actual_network_data.cpp
- networks/aprox19/actual_network.H
- networks/aprox19/actual_network_data.cpp
- networks/aprox21/actual_network.H
- networks/aprox21/actual_network_data.cpp
- networks/ignition_simple/actual_network.H
- networks/ignition_simple/actual_network_data.cpp
- networks/iso7/actual_network.H
- networks/iso7/actual_network_data.cpp
- nse_solver/nse_solver.H
we used to have `init_nse_net` to compute `rate_indices`, but now we generate them directly. Therefore, it is really not needed anymore.
> remove init_nse_net

- nse_solver/nse_check.H
abort earlier if T_in < T_nse_net to avoid unnecessary computing.
> abort earlier if T_in < T_nse_net

- EOS/helmholtz/actual_eos.H
- integration/VODE/actual_integrator.H
- interfaces/ArrayUtilities.H
- interfaces/burn_type.H
- interfaces/eos_type.H
- interfaces/rhs_type.H
- networks/aprox13/actual_network.H
- networks/aprox21/actual_network.H
- networks/iso7/actual_network.H
- networks/rhs.H
- nse_solver/nse_solver.H
- screening/screen_data.H
- unit_test/test_react/main.cpp
- unit_test/test_rhs/rhs_zones.H
Along with #1287, this resolves all the remaining warnings I could find with `burn_cell` and `test_rhs`.
> Fix remaining clang-tidy warnings

- networks/aprox13/actual_network.H
- networks/aprox19/actual_network.H
- networks/aprox21/actual_network.H
- networks/ignition_simple/actual_network.H
- networks/iso7/actual_network.H
- networks/powerlaw/actual_network.H
- networks/rhs.H
- networks/triple_alpha_plus_cago/actual_network.H
This prepares for the conversion of ignition_chamulak, which determines the energy release based on the current density.
> Add rhs_state to ener_gener_rate interface

- interfaces/rhs_type.H
- networks/aprox13/actual_network.H
- networks/aprox19/actual_network.H
- networks/aprox21/actual_network.H
- networks/ignition_simple/actual_network.H
- networks/iso7/actual_network.H
- networks/powerlaw/actual_network.H
- networks/triple_alpha_plus_cago/actual_network.H
- sphinx_docs/source/templated_networks.rst
This supports conversion of ignition_chamulak to the new reactions scheme. It should also allow replacement of the branching ratio, at least in some cases, with a direct modification to the number of reactants consumed.
> Convert rhs_t number of reactions from int to real

- .github/workflows/hip.yml
subch_simple takes nearly an hour to link, so it's suboptimal as a CI test. This ensures we still have pynucastro coverage but is significantly faster.
> Switch to a simpler pynucastro net for HIP CI

- EOS/gamma_law/actual_eos.H
- EOS/primordial_chem/actual_eos.H
- interfaces/eos_type.H
This PR adds the `eos_input_rp` mode for primordial chem EOS. It also computes the sound speed and stores it in `state.cs` if pressure is defined.
> Compute thermodynamic derivatives and implement dens+pres mode in primordial chem EOS

- EOS/gamma_law/actual_eos.H
- EOS/primordial_chem/actual_eos.H
- interfaces/eos_type.H
This fixes invocations of gamma_law with types other than eos_t.
> Add has_G to check if G is in the EOS type

- screening/Make.package
- screening/screen.H
- screening/screen_data.H
- screening/screen_data.cpp
All networks using this legacy approach have now been converted to use the new interface that doesn't rely on the vector of screening factors.
> Remove legacy screening interface

- requirements.txt
Breathe is currently incompatible with Sphinx >= 7.2: see https://github.com/breathe-doc/breathe/issues/943.
> Constrain Sphinx version to fix docs build

- .github/workflows/cmake_build_cell_primordial_chem.yml
- .github/workflows/macos_build_cell_primordial_chem.yml
- CMakeLists.txt
We were generating `network_properties.H` for primordial chem twice. 
Also changed AMReX related variable names to use lowercase 'e'
> CMake: do not generate network_properties twice

- requirements.txt
Sphinx 7.2.3 was released today, which includes a fix for the Breathe incompatibility.
> Remove Sphinx version constraint

- nse_solver/nse_solver.H
- screening/screen.H
This reduces code duplication and lets us reuse it in the NSE solver.
Also pull some common subexpressions into variables so we only calculate them once.
> Move Helmholtz free energy from chabrier1998 into a helper function

- integration/VODE/vode_dvhin.H
- integration/VODE/vode_dvode.H
- integration/VODE/vode_dvstep.H
- integration/integrator_data.H
- interfaces/burn_type.H
this will make it more in line with how simplified-SDC works
> update true-SDC to be in sync with upcoming Castro cleaning

- CMakeLists.txt
We don't want to include general_null in the directories for primordial chem
> Remove general_null from primordial chem

- integration/RKC/rkc_type.H
- integration/VODE/vode_type.H
- integration/integrator_data.H
we can basically do what simplified-SDC does now
> some more true-SDC simplication

- EOS/helmholtz/actual_eos.H
> make sure we are actually getting lines from helm_table.dat

- neutrinos/sneut5.H
no need to set these each time we enter the function
> move some Fermi integral coefficients to static arrays

- EOS/gamma_law/_parameters
- EOS/helmholtz/_parameters
- Make.Microphysics
- integration/_parameters
- networks/_parameters
- nse_solver/_parameters
- util/build_scripts/write_probin.py
when we originally did the Fortran -> C++ conversion, we passed all of the Fortran logicals into C++ ints.  But now that we are completely C++, it doesn't make sense to have logical anymore.  There are some places where we implicitly pass an int to a C++ bool.  This will help track those down and eliminate things.
> don't allow logical runtime parameters

- integration/nse_update_simplified_sdc.H
this will allow them to be disabled at compile-time just like we do for a network
> wrap SDC+NSE neutrino calls with NEUTRINOS

- .github/workflows/c-linter.yml
We were previously testing a bunch of invalid preprocessor configurations, which we can now exclude. Installing all the build tools is unnecessary since the linter step runs inside its own Docker container.
> Update C++ linter settings to speed up cppcheck

- nse_tabular/nse_table.H
- unit_test/test_nse_interp/ci-benchmarks/aprox19.out
- unit_test/test_nse_interp/nse_cell.H
this works by differentiating the cubic interpolant
> add a method to compute the T derivative of an NSE table quantity

- nse_solver/_parameters
- nse_solver/nse_check.H
- sphinx_docs/source/nse.rst
I was playing around with the NSE compatibility script and found the original molar fraction check a bit too strict, where the mass fractions might be already sufficient for the forward and reverse equilibrium conditions but still don't pass the molar fraction check.
Here I added another one comparing the molar fraction of each species.
> add additional molar fraction check for NSE_NET

- util/build_scripts/runtime_parameters.py
- util/build_scripts/write_probin.py
this will be used to make runtime parameters no longer managed
> add struct support for runtime_parameters.py

- .github/workflows/burn_cell.yml
- .github/workflows/burn_cell_primordial_chem.yml
- .github/workflows/burn_cell_sdc.yml
- .github/workflows/c-linter.yml
- .github/workflows/castro.yml
- .github/workflows/check-ifdefs.yml
- .github/workflows/cmake_build_cell_primordial_chem.yml
- .github/workflows/codespell.yml
- .github/workflows/compile_action.yml
- .github/workflows/compiler-warnings.yml
- .github/workflows/create_release.yml
- .github/workflows/cuda.yml
- .github/workflows/docs-test.yml
- .github/workflows/eos_cell.yml
- .github/workflows/gh-pages.yml
- .github/workflows/hip.yml
- .github/workflows/macos_build_cell_primordial_chem.yml
- .github/workflows/nse_net.yml
- .github/workflows/nse_table.yml
- .github/workflows/nse_test.yml
- .github/workflows/style.yml
- .github/workflows/test_neutrinos.yml
- .github/workflows/test_nse_interp.yml
- .github/workflows/test_rhs.yml
also use the cache built into setup_python
> update github actions to latest versions

- networks/update_pynucastro_nets.py
This should help with the spurious roundoff diffs when regenerating the networks.
> Disable SVML AVX-512 routines in the pyna update script

- integration/VODE/vode_dvjac.H
- integration/VODE/vode_dvnlsd.H
- integration/VODE/vode_dvstep.H
- integration/VODE/vode_type.H
This addresses #1451, which was caused by the pivot array being reused for the first time in a new step when the Jacobian had been cached without keeping the corresponding values of the pivot array in scope.
> Move pivot into the VODE state

- integration/BackwardEuler/actual_integrator.H
- integration/BackwardEuler/actual_integrator_sdc.H
- integration/ForwardEuler/actual_integrator.H
- integration/QSS/actual_integrator.H
- integration/RKC/actual_integrator.H
- integration/RKC/actual_integrator_sdc.H
- integration/VODE/actual_integrator.H
- integration/VODE/actual_integrator_sdc.H
This reduces the compilation time for gcc by ~50% and CUDA by ~90%. HIP still takes forever to link, unfortunately.
> Don't force-inline actual_integrator()

- integration/nse_update_sdc.H
This accounts for the fact that when we just do the binding energy, we don't capture the energy difference from converting protons to neutrons.  That term looks like N_A (m_n - (m_p + m_e) c**2 dY_e/dt.  This adds that to the SDC
update.
> add missing weak rate energy to NSE update

- integration/nse_update_sdc.H
This is a small change, but makes us consistent with have a prediction for the energy evolution from NSE
> add d<B/A>/dt to the predictor for the NSE+SDC update

- .github/workflows/hip.yml
Also remove COMP=gnu, since it's redundant, and bump up the number of parallel make jobs to 4.
> Disable force-inlining in HIP CI

- .github/workflows/hip.yml
- Make.Microphysics_extern
this works around some issues with large kernels and ROCm
> if we are building with HIP, don't force inlining

- networks/rhs.H
in particular, IArray1D was `int` here, but `short` in integrator_data.H
> remove redundant (and conflicting) typedefs in rhs.H

- networks/rhs.H
- unit_test/burn_cell/ci-benchmarks/chamulak_VODE_unit_test.out
this was wrong, but turns out, it had no effect because of a bug in the logic of the is_jacobian_term_used.  That issue is also fixed here, and the function is kept for use in the future.
> remove the is_jacobian_term_used logic in the linear algebra

- integration/nse_update_sdc.H
also clean up the logic some so it is clear we are using the value from the last nse table call
> remove an unused compute of abar1_out in nse

- neutrinos/sneut5.H
clang-tidy: misc-confusable-identifiers
> rename f1 to tmp to avoid confusion with fl

- networks/CNO_extras/partition_functions.H
- networks/ECSN/partition_functions.H
- networks/He-C-Fe-group/partition_functions.H
- networks/He-C-Fe-group/reaclib_rates.H
- networks/ase/partition_functions.H
- networks/ase/reaclib_rates.H
- networks/ignition_reaclib/C-burn-simple/partition_functions.H
- networks/ignition_reaclib/URCA-medium/partition_functions.H
- networks/ignition_reaclib/URCA-simple/partition_functions.H
- networks/nova/partition_functions.H
- networks/nova2/partition_functions.H
- networks/partition_test/partition_functions.H
- networks/partition_test/reaclib_rates.H
- networks/sn160/partition_functions.H
- networks/subch_approx/partition_functions.H
- networks/subch_base/partition_functions.H
- networks/subch_base/reaclib_rates.H
- networks/subch_full/partition_functions.H
- networks/subch_simple/partition_functions.H
Includes improvements from pynucastro/pynucastro#726.
> Update pynucastro networks for derived rate speedup

- .clang-tidy
> have clang-tidy warn about recursion

- integration/RKC/actual_integrator.H
- integration/RKC/actual_integrator_sdc.H
- integration/RKC/rkc.H
- integration/RKC/rkc_type.H
- integration/VODE/actual_integrator.H
- integration/VODE/actual_integrator_sdc.H
- integration/VODE/vode_dvjac.H
- integration/VODE/vode_dvnlsd.H
- integration/VODE/vode_dvode.H
- integration/VODE/vode_dvstep.H
- integration/VODE/vode_type.H
- integration/utils/rkc_util.H
this will make it easier to merge a lot of integrator logic
now VODE, BackwardEuler, and RKC all use the same names
> standardize names for # of rhs calls, Jac evals, and steps

- sphinx_docs/rp.py
- sphinx_docs/source/integrators.rst
- sphinx_docs/source/nse.rst
- sphinx_docs/source/rp_intro.rst
Group by namespace and prettify the category description, and fix some cross-references elsewhere in the docs.
> Rework runtime parameter docs

- sphinx_docs/source/ode_integrators.rst
this was probably a merge issue
> remove duplicate renormalization section from docs

- integration/_parameters
- integration/integrator_setup_sdc.H
- integration/integrator_setup_strang.H
- sphinx_docs/source/ode_integrators.rst
they now default to -1, in which case the original (non-retry) tolerance will be used.  This makes it easier for a user to use the retry mechanism without having to remember to explicitly set all of the tolerances
> change how the retry tolerances work

- sphinx_docs/source/autodiff.rst
- sphinx_docs/source/index.rst
- sphinx_docs/source/refs.bib
- util/Make.package
- util/microphysics_autodiff.H
This adds a new header, `microphysics_autodiff.H`, which includes the autodiff library and sets things up for use with AMReX. It also provides the `admath` namespace, which is a drop-in replacement for `std` for functions from `<cmath>`, and works on both autodiff types and normal numeric types.
> Add autodiff machinery and docs

- screening/screen.H
- sphinx_docs/source/autodiff.rst
Also document `autodiff::detail::isDual` for checking templated types.
I'm leaving this as a quiet NaN so it will show up in outputs if it ever gets used by accident, but won't immediately trigger a floating-point exception.
> Fix FPE in templated networks

- integration/VODE/vode_dvjac.H
- networks/rhs.H
- unit_test/test_linear_algebra/test_linear_algebra.H
`RHS::dgefa()` now stops if the matrix is singular, and returns an integer that works the same as the `info` parameter for the routine in `linpack.H`. If the LU decomposition fails, it is the index of the row that failed, and is zero if the decomposition succeeded.
This fixes the crash in `Detonation-collision-retry-SDC` in the Castro test suite. The benchmark does need to be updated, since it now stops at step 10 instead of 11, and the plotfile for that step was last updated before we changed the setup in https://github.com/AMReX-Astro/Castro/pull/2806.
> Avoid dividing by zero in constexpr linear algebra routines

- rates/aprox_rates.H
I found these while comparing against a version that I updated to use autodiff.
> Fix some errors in the aprox network rate derivatives

- unit_test/burn_cell/ci-benchmarks/chamulak_VODE_unit_test.out
- util/autodiff/autodiff/forward/dual/dual.hpp
- util/microphysics_autodiff.H
In my testing with converting the `aprox*` rates to use autodiff, I found a lot of instances where code templated with `autodiff::dual` would give slightly different values than the same code templated with `amrex::Real`. It turns out to be due to some optimizations autodiff makes to speed up evaluation, which this PR disables to avoid any weird inconsistencies in the future.
> Update `autodiff::dual` to give the same results as `amrex::Real`

- interfaces/rhs_type.H
- networks/aprox13/actual_network.H
- networks/aprox19/actual_network.H
- networks/aprox21/actual_network.H
- networks/ignition_chamulak/actual_network.H
- networks/ignition_simple/actual_network.H
- networks/iso7/actual_network.H
- networks/powerlaw/actual_network.H
- networks/rhs.H
- networks/rprox/actual_network.H
- networks/triple_alpha_plus_cago/actual_network.H
- screening/screen.H
- sphinx_docs/source/autodiff.rst
- unit_test/test_screening_templated/screening_util.cpp
This is more accurate, as it may be either `amrex::Real` or a dual type.
No functional changes.
> Rename the numeric type template parameter from dual_t to number_t

- networks/CNO_extras/actual_rhs.H
- networks/ECSN/actual_rhs.H
- networks/He-C-Fe-group/actual_rhs.H
- networks/ase/actual_rhs.H
- networks/ignition_reaclib/C-burn-simple/actual_rhs.H
- networks/ignition_reaclib/URCA-medium/actual_rhs.H
- networks/ignition_reaclib/URCA-simple/actual_rhs.H
- networks/nova/actual_rhs.H
- networks/nova2/actual_rhs.H
- networks/partition_test/actual_rhs.H
- networks/sn160/actual_rhs.H
- networks/subch_base/actual_rhs.H
- networks/subch_simple/actual_rhs.H
https://github.com/pynucastro/pynucastro/pull/759
> Rename dual_t in pynucastro networks

- integration/integrator_setup_strang.H
If state.xn contains number densities (e.g., for primordial and metal chemistry), it can be hard to read large values when they are not printed in scientific format. This is not an issue for other cases where mass fractions are being used, since they are always <=1 .
> display state.xn in scientific notation

- CMakeLists.txt
- networks/primordial_chem/actual_network.H
- networks/primordial_chem/actual_network_data.cpp
- unit_test/burn_cell_primordial_chem/burn_cell.H
We now use a function that does the charge balance for primordial chemistry, similar to that done for metal chemistry in #1642
> Remove hardcoded charge balance in primordial chemistry

- networks/primordial_chem/pynucastro.net
Even though there is no dust in primordial chemistry, we define Tdust as an auxiliary variable so that we don't need to differentiate between primordial and metal chemistry in quokka. For additional context, see line https://github.com/psharda/quokka/blob/metal_chem/src/chemistry/Chemistry.hpp#L99, which will be added to quokka via https://github.com/quokka-astro/quokka/pull/723
> Define Tdust as an auxiliary variable in primordial chemistry

- networks/metal_chem/_parameters
Turns out that we don't actually need a parameter to differentiate between ice and gas species indices in quokka.
> Remove unused param

- unit_test/burn_cell/GNUmakefile
- unit_test/burn_cell/_parameters
- unit_test/burn_cell/burn_cell.H
if this is True, then we don't need to specify the mass fractions individually, instead they are all initialized to X = 1/NumSpec
> add a init_species_all_equal option to burn_cell

- integration/integrator_setup_strang.H
- sphinx_docs/source/integrators.rst
- sphinx_docs/source/nse.rst
- sphinx_docs/source/ode_integrators.rst
- sphinx_docs/source/refs.bib
These were out of sync in a lot of places.  Also, now all of the runtime parameters are documented.
> update the integration and NSE docs

- interfaces/eos.H
> remove use_raw_inputs

- .codespell-ignore-words
- integration/utils/numerical_jacobian.H
> fix some codespell issues

- Docs/source/burn_cell.rst
- unit_test/_parameters
- unit_test/burn_cell/_parameters
- unit_test/burn_cell/burn_cell.H
- unit_test/burn_cell_sdc/burn_cell.H
- unit_test/eos_cell/eos_cell.H
- unit_test/jac_cell/jac_cell.H
- unit_test/react_util.H
- unit_test/test_react/_parameters
test_react had already implemented uniform_xn, so now we bump that runtime parameter up a level so all unit tests can use it.
This also updates `eos_cell`, `burn_cell_sdc`, and `jac_cell` to support this feature.
> remove duplicate init_species_all_equal in favor of uniform_xn

- Docs/source/comprehensive_tests.rst
- Docs/source/unit_test_runtime_parameters.rst
- unit_test/react_util.H
- unit_test/test_eos/_parameters
- unit_test/test_eos/eos_util.cpp
- unit_test/test_eos/input_eos
- unit_test/test_eos/input_eos.multigamma
- unit_test/test_eos/input_eos.polytrope
- unit_test/test_eos/input_eos.tillotson
- unit_test/test_eos/main.cpp
- unit_test/test_eos/test_eos.H
this allows it to work with any network, not just one with H1 and He4
> update test_eos to use composition runtime parameters

- Docs/source/nse_net.rst
- integration/nse_update_sdc.H
- nse_solver/nse_eos.H
- unit_test/nse_net_cell/ci-benchmarks/nse_net_unit_test.out
Addresses the following:
1) Fix the issue that abar wasn't calculated correctly. Needed to take the reciprocal in the end.
2) Switch to use central difference rather than 5-stencil to compute dabardT. Convergence test shows that central difference is sufficient for 2nd order.
3) Construct the reactive source term for rho e directly, instead of evolving for tau and do a finite difference to get the derivative.
> update nse_sdc_burn for NSE_NET
