AMReX-Astro/Microphysics

integration/VODE/rpar.F90

I'm not sure the effects this has, but it seems apparent this needs fixing.

Fix indexing into rpar for VODE SDC.

---

integration/BS/bs_jac.F90
integration/BS/bs_rhs.F90
integration/VBDF/bdf_rhs.f90
integration/VODE/vode_rhs.f90
integration/VODE90/vode_rhs.f90
integration/_parameters

add the ability to boost the reaction rates

add the ability to boost the reaction rate

---

EOS/helmholtz/actual_eos.F90

this marks all of the internal table functions as pure, in hopes that some compilers might find that info useful.

move the internal EOS functions to pure functions

---

README.md

add development and contribution notes

---

unit_test/burn_cell/burn_cell_compare_2tests.py
unit_test/burn_cell/burn_cell_compare_abs.py
unit_test/burn_cell/burn_cell_compare_rel.py
unit_test/burn_cell/burn_cell_testing.py

burn_cell_testing.py can run in place of burn_cell.py. This creates files that allow the following codes to run:
~burn_cell_compare_rel.py will make relative comparisons between a reference burn_cell run and a series of runs following.
~burn_cell_compare_abs.py will make absolute comparisons between  a reference burn_cell run and a series of runs following.
~burn_cell_compare_2tests.py will show the mass fraction, Moller fraction, temperature, and energy change graphs of two burn_cell runs in the same file.

Created 4 plotting codes for analysis of burn_cell unit tests.

---

unit_test/burn_cell/README.txt
unit_test/burn_cell/burn_cell_compare_2tests.py
unit_test/burn_cell/burn_cell_compare_abs.py
unit_test/burn_cell/burn_cell_compare_rel.py
unit_test/burn_cell/burn_cell_testing.py

Created scripts to plot relative and absolute errors of mass fraction, moller fraction, temperature, and energy generation rate. A third code will plot the graphs generated by burn_cell.py for two different runs on the same figure.
README.txt explains how to do this.

Burn_cell relative/absolute error plotter and two test grapher. 

---

unit_test/burn_cell/burn_cell_compare_2tests.py

In burn_cell_compare_2tests.py, changed graph file names from ..._2networks.png to ..._2tests.png

Changed graph file naming convention to match the name of the script.

---

integration/numerical_jacobian.f90

These were missing a factor of A, so the Jacobian was actually using d(Y-dot) / dX.
Fixes #92

Fix the calculation of the numerical Jacobian terms wrt X

---

rates/GPackage.mak
rates/Make.package
rates/aprox_rates.F90
rates/tfactors.F90

This marks up the rates module subroutines for CUDA.

Mark up rates module used by aprox networks for CUDA

---

screening/screen.F90

this fixes an issue in the blending of the screening reported by Rob Farmer, #149

Screen fix

---

CHANGES
EOS/helmholtz/_parameters

change eos_input_is_constant to true

---

util/skynet/README.md
util/skynet/burn.py
util/skynet/compare.py

First pull request, hope I did this right!

Adding skynet utilities to burn or compare to star-killer

---

integration/VODE90/vode_rhs.F90
integration/VODE90/vode_type.F90

sync up with VODE
This now implements the react_boost

VODE90 sync

---

integration/utils/nonaka_plot.f90

ydot is allocated for nspec_evolve + 2, so looping over nspec will go out of bounds

nspec -> nspec_evolve

---

EOS/composition.F90
EOS/helmholtz/actual_eos.F90

mostly unused variables when we are not using `EXTRA_THERMO`

clean up some compiler warnings

---

rates/tfactors.F90

remove unused tfactors

---

networks/aprox13/actual_network.F90
networks/aprox19/actual_network.F90
networks/aprox21/actual_network.F90
networks/ignition_chamulak/actual_network.F90
networks/ignition_simple/actual_network.F90

this addresses #122 
Note the pynucastro nets will be dealt with separately by updating pynucastro.

remove wion -- it is unused

---

networks/iso7/actual_rhs.F90

this was caught by the C++ assert

fix O16+O16 screening setup

---

integration/VODE/vode_rhs.F90
integration/VODE/vode_rhs.H

This allows us to hit the floor or ceiling and then just ride that to the final integration time.

Zero out rates if temperature hits the floor or ceiling

---

.github/workflows/create_release.yml
.github/workflows/get_release_txt.py

This adds a github action which automatically creates a release whenever a tag of the form xx.xx is created. The release text is scraped from `CHANGES.md`.

Release action

---

interfaces/network.F90
interfaces/network.H

This adds "get" routines for the auxillary indices in both Fortran and C++

add get routines for aux

---

unit_test/test_eos/eos_util.cpp
unit_test/test_eos/eos_util_F.F90

the F90 one in particular gets printed by each GPU thread

remove prints

---

interfaces/eos.H

remove has_been_reset from reset_rho and reset_T

---

EOS/Make.package
interfaces/Make.package
unit_test/burn_cell/main.cpp

(we also need USE_CXX_REACTIONS=FALSE)
closes #376

this gets burn_cell compiling with USE_CXX_EOS=FALSE

---

EOS/gamma_law/actual_eos.H

for some inputs, we were not defining the sound speed or derivatives

fill in more of the gamma law state

---

conductivity/constant/actual_conductivity.H
conductivity/constant_opacity/actual_conductivity.H
conductivity/powerlaw/actual_conductivity.H
conductivity/stellar/actual_conductivity.H
integration/VODE/cuVODE/test/main.cpp
networks/ignition_simple/test-cpp/main.cpp
unit_test/burn_cell/main.cpp
unit_test/eos_cell/main.cpp
unit_test/test_aprox_rates/main.cpp
unit_test/test_aprox_rates/test_aprox_rates.H
unit_test/test_conductivity/main.cpp
unit_test/test_conductivity/test_cond.H
unit_test/test_cvode_react/main.cpp
unit_test/test_cvode_react/react_cuda.cpp
unit_test/test_cvode_react/react_cuda_cusolver.cpp
unit_test/test_cvode_react/react_serial.cpp
unit_test/test_eos/main.cpp
unit_test/test_eos/test_eos.H
unit_test/test_parameters/main.cpp
unit_test/test_react/main.cpp
unit_test/test_rhs/main.cpp
unit_test/test_screening/main.cpp
unit_test/test_screening/test_screen.H
unit_test/test_sdc/main.cpp
unit_test/write_job_info.cpp

done via:
```
for i in `git grep -l "#include \""`; do sed -r -i -E "s/#include \"(\w+\.\w+)\"/#include <\1>/g" $i; done
```

switch includes from "" to <>

---

networks/aprox19/Make.package

these may have gotten lost in the NSE merge

add some C++ files missing in Make.package

---

unit_test/burn_cell/burn_cell.F90

cs and dx were removed from the burn_t

---

networks/aprox13/actual_rhs.F90
networks/aprox13/actual_rhs.H
networks/aprox19/actual_rhs.F90
networks/aprox19/actual_rhs.H
networks/aprox21/actual_rhs.F90
networks/ignition_chamulak/actual_rhs.F90
networks/ignition_simple/actual_rhs.F90
networks/ignition_simple/actual_rhs.H
networks/iso7/actual_rhs.F90
networks/iso7/actual_rhs.H
networks/rate_type.H
networks/rate_type.f90
networks/rprox/actual_rhs.F90
networks/triple_alpha_plus_cago/actual_rhs.F90
networks/triple_alpha_plus_cago/actual_rhs.H
networks/xrb_simple/actual_rhs.f90

Remove T_eval from rate_t

---

integration/ForwardEuler/Make.package
integration/ForwardEuler/README.md
integration/ForwardEuler/_parameters
integration/ForwardEuler/actual_integrator.H

This will be useful for testing purposes going forward as we experiment with new integration schemes.
The timestepping scheme is not sophisticated right now and so the integrator has trouble in the NSE regime -- this should be fixed later.
Only Strang is provided for now.

Add a simple forward Euler integrator

---

util/esum.H
util/esum_cxx.py

This splits off the esum part of #413.

Add templated esum implementation

---

unit_test/react_util.H

setup_composition does not need to be on the GPU

---

sphinx_docs/source/basics.rst
sphinx_docs/source/integrators.rst

some documentation updates

---

EOS/breakout/actual_eos.H
EOS/eos_composition.H
EOS/gamma_law/actual_eos.H
EOS/gamma_law_general/actual_eos.H
EOS/helmholtz/actual_eos.H
EOS/multigamma/actual_eos.H
EOS/multigamma/eos_composition.H
EOS/polytrope/actual_eos.H
EOS/rad_power_law/actual_eos.H
EOS/ztwd/actual_eos.H
conductivity/constant/actual_conductivity.H
conductivity/constant_opacity/actual_conductivity.H
conductivity/powerlaw/actual_conductivity.H
conductivity/stellar/actual_conductivity.H
integration/VODE/vode_type_simplified_sdc.H
interfaces/burn_type.H
interfaces/conductivity.H
interfaces/eos.H
interfaces/eos_override.H

Starts #470 by making all functions which previously accepted an eos_t be templated.

Template functions which accept an eos_t

---

Make.Microphysics
Make.Microphysics_extern

this will let us test on STRANG and simplify some preprocessor logic

define STRANG if we are not doing an SDC variant

---

.github/workflows/get_release_txt.py

this will hopefully fix the release notes

sync the release script with Castro

---

integration/VODE/Make.package
integration/VODE/vode_dvjac.H
integration/VODE/vode_dvnlsd.H
util/Make.package
util/linpack.H

Generalize linpack and move to util

---

networks/aprox13/actual_rhs.H
networks/aprox19/actual_rhs.H
networks/ignition_simple/actual_rhs.H
networks/iso7/actual_rhs.H
networks/powerlaw/actual_rhs.H
networks/triple_alpha_plus_cago/actual_rhs.H

in particular, this is now safe for true SDC

only do the temperature RHS and Jac for Strang

---

util/build_scripts/runtime_parameters.py

this change allows MAESTROeX to use the same parameter script

more param tweaks for MAESTROeX

---

util/build_scripts/runtime_parameters.py

now they are all allocated in Fortran the same regardless if
we are coming in from Fortran or C++.  This requires changes
on the application code side.

clean up strings in runtime_parameters.py

---

integration/Make.package
integration/VODE/Make.package
integration/VODE/cuVODE/source/cuvode_dvjac.F90
integration/VODE/vode_dvhin.H
integration/VODE/vode_dvjac.H
integration/VODE/vode_dvode.H
integration/VODE/vode_type.H
integration/utils/Make.package
integration/utils/jacobian_sparsity.F90
integration/utils/numerical_jacobian.H
integration/utils/temperature_integration.H
interfaces/Make.package
interfaces/burn_type.H
interfaces/burner.H
interfaces/microphysics.F90
networks/aprox13/Make.package
networks/aprox19/Make.package
networks/aprox21/Make.package
networks/breakout/Make.package
networks/general_null/Make.package
networks/ignition_chamulak/Make.package
networks/ignition_simple/Make.package
networks/iso7/Make.package
networks/powerlaw/Make.package
networks/rprox/Make.package
networks/triple_alpha_plus_cago/Make.package
networks/xrb_simple/Make.package

in particular, this will allow Castro's true-SDC work

change the if logic for the RHS include in C++ VODE

---

integration/VODE/Make.package
integration/VODE/vode_dvjac.H
integration/VODE/vode_type.H

allow us to enable jacobian caching even on the GPU

---

.github/workflows/create_release.yml

we were not sending the release text for the environment

fix create_release action

---

unit_test/test_react/inputs_aprox13

1e-3 seconds is a little hard to achieve for the burns that already burn to NSE

Decrease tmax for aprox13 burn

---

integration/ForwardEuler/actual_integrator.H

Applies the approach from #471 and #496 to the ForwardEuler integrator. (The QSS integrator already does this.)

Set ForwardEuler integrator to integrate e but not T

---

networks/aprox19/_parameters
networks/aprox19/nse.H
networks/aprox19/nse_check.F90

this allows us to better capture the regions where NSE should hold

add checks on O and Si to the NSE check

---

networks/aprox13/actual_rhs.H

Fold more proton links into the alpha chain

aprox13 5/∞

---

networks/aprox19/actual_rhs.H

Move identical particle factors into rates

aprox19 1/∞

---

networks/aprox13/actual_rhs.H

aprox13 10/∞

---

integration/ForwardEuler/actual_integrator.H
integration/QSS/actual_integrator.H
integration/VODE/actual_integrator.H
integration/VODE/vode_type_strang.H
integration/utils/numerical_jacobian.H
interfaces/burn_type.H

For now, only the Strang paths are updated.

Call EOS using burn_t

---

networks/aprox13/actual_network.H
networks/aprox13/actual_rhs.H

Remove proton links from rates list

aprox13 11/∞

---

networks/aprox13/actual_network.H
networks/aprox13/actual_rhs.H

Move aprox13 over to new RHS scheme

aprox13 13/∞

---

networks/aprox13/actual_network.H
networks/aprox13/actual_rhs.H

Create RHS-specific version of energy RHS

aprox13 14/∞

---

integration/VODE/vode_dvjac.H
integration/VODE/vode_rhs_simplified_sdc.H
integration/_parameters

We compute the Jacobian as J = dR/dw dw/dU
this will construct dw/dU analytically but dR/dw numerically

add a jacobian = 3 option for simplified SDC

---

interfaces/eos_type.H

eos_rep_t has everything needed for p and e

add 2 new EOS types

---

interfaces/burn_type.H
unit_test/test_sdc/react_zones.H

we no longer require these for the update

remove the lagged reaction terms from simplified-SDC

---

util/build_scripts/runtime_parameters.py

Signed-off-by: Michael Zingale <michael.zingale@stonybrook.edu>

another runtime param fix for bool fortran params in C++

---

util/build_scripts/runtime_parameters.py

this adds the C++ queryarr logic to support specifying values for array
runtime parameters in an inputs file or on the commandline

allow for runtime parameter arrays to be read at runtime

---

integration/VODE/vode_rhs.H

previously, we were checking on the old T, not the T corresponding to the
current e that we are trying to integrate with.

move the check that the temperature is reasonable after we update thermo

---

EOS/Make.package
EOS/breakout/Make.package
EOS/gamma_law/Make.package
EOS/helmholtz/Make.package
EOS/multigamma/Make.package
EOS/polytrope/Make.package
EOS/rad_power_law/Make.package
EOS/stellarcollapse/Make.package
EOS/tillotson/Make.package
EOS/ztwd/Make.package
Make.Microphysics_extern
interfaces/Make.package
interfaces/microphysics.F90
networks/Make.package
networks/general_null/Make.package
networks/general_null/write_network.py
unit_test/test_eos/Make.package
unit_test/test_eos/main.cpp

this works in tandem with USE_FORT_EOS

create USE_FORT_MICROPHYSICS to enable/disable the Fortran network build

---

integration/integrator.H
integration/integrator_sdc.H
interfaces/burner.H

we lost this in the F90 -> C++ port
this closes #667

implement the abort_on_failure functionality

---

integration/VODE/vode_type_simplified_sdc.H

fix the scaling of species before the EOS call for SDC

---

interfaces/burner.H
networks/aprox19/_parameters
networks/aprox19/nse.H

if the burn fails and we are close to NSE, we relax the NSE check
by this factor (< 1) to allow us to enter NSE.

add an NSE relax factor, network.nse_relax_factor

---

unit_test/test_sdc/react_zones.H

burn_state.T_from_eden no longer exists

fix test_sdc compilation

---

networks/aprox13/actual_network.H

Add intermediate links to NumRatesFR

aprox13 17/∞

---

networks/aprox13/actual_rhs.H

Use auto species_rhs for d(rate)/dT in Jacobian

aprox13 18/∞

---

integration/VODE/vode_rhs_simplified_sdc.H
integration/utils/numerical_jacobian.H

in particular, when we perturb X, T changes

for the numerical Jacobian, fix some of the thermodynamics

---

unit_test/react_util.H
unit_test/test_jac/_parameters
unit_test/test_jac/main.cpp
unit_test/test_react/_parameters
unit_test/test_react/main.cpp
unit_test/test_rhs/_parameters
unit_test/test_rhs/main.cpp
unit_test/test_sdc/_parameters
unit_test/test_sdc/main.cpp

This is useful for performance testing

Add option for uniform composition in unit tests

---

integration/utils/numerical_jacobian.H

now we difference in terms of T, X_k, but convert to e, X_k

redo the numerical Jacobian (again)

---

unit_test/burn_cell_sdc/GNUmakefile
unit_test/burn_cell_sdc/Make.package
unit_test/burn_cell_sdc/_parameters
unit_test/burn_cell_sdc/burn_cell.H
unit_test/burn_cell_sdc/inputs_aprox19
unit_test/burn_cell_sdc/inputs_aprox19_failure
unit_test/burn_cell_sdc/main.cpp
unit_test/burn_cell_sdc/parse_integration_failure.py

this will help investigate SDC failures

add a single zone SDC burn test

---

interfaces/burn_type.H

also for SDC, label the important terms

make the burn_state << output have more precision

---

sphinx_docs/source/conf.py

Updates conf.py to fix things after a recent Sphinx update

Fix the docs build

---

.github/workflows/compile_action.yml
.github/workflows/find_changed_files.py

This compiles the two tests `burn_cell` and `test_eos` when changes are made to the Microphysics repo.

Add action to compile code when pushed to remote

---

networks/general_null/Make.package
networks/general_null/actual_network.H
networks/general_null/actual_network_data.cpp
networks/general_null/actual_rhs.H
networks/general_null/actual_rhs_data.cpp

Give general_null the option to compile/run on GPU.

General null gpu

---

unit_test/test_react/inputs_3alpha
unit_test/test_react/inputs_aprox13
unit_test/test_react/inputs_aprox19
unit_test/test_react/inputs_aprox19.nse_disabled
unit_test/test_react/inputs_aprox19_nse
unit_test/test_react/inputs_aprox21
unit_test/test_react/inputs_ignition
unit_test/test_react/inputs_ignition_chamulak
unit_test/test_react/inputs_iso7
unit_test/test_react/inputs_nova
unit_test/test_react/inputs_powerlaw
unit_test/test_react/inputs_reaclib_cburn
unit_test/test_react/inputs_reaclib_ctest
unit_test/test_react/inputs_reaclib_urca
unit_test/test_react/inputs_rprox
unit_test/test_react/inputs_sn160
unit_test/test_react/inputs_xrb_simple

we no longer read the file if it doesn't exist

remove probin stub -- that was a temporary hack

---

interfaces/fortran_to_cxx_actual_rhs.H

we were not accessing the energy component

fix the Fortran Jacobian wrapper for J_E_E

---

unit_test/test_rhs/_parameters
unit_test/test_rhs/inputs_aprox13
unit_test/test_rhs/inputs_aprox19
unit_test/test_rhs/inputs_aprox21
unit_test/test_rhs/inputs_ecsn
unit_test/test_rhs/inputs_ignition_simple
unit_test/test_rhs/inputs_nova
unit_test/test_rhs/inputs_powerlaw
unit_test/test_rhs/inputs_rprox
unit_test/test_rhs/inputs_triple_alpha_plus_cago

also remove tmax -- it is not used for this test

add inputs for nova and ECSN

---

unit_test/burn_cell_sdc/_parameters
unit_test/burn_cell_sdc/burn_cell.H
unit_test/burn_cell_sdc/parse_integration_failure.py

these gives more flexibility in creating the inputs for burn_cell_sdc
from an integration failure

some burn_cell_sdc changes

---

integration/VODE/_parameters
integration/VODE/vode_dvstep.H
integration/VODE/vode_type.H

synchronize the strang and SDC step rejection logic

---

integration/VODE/vode_rhs_simplified_sdc.H

we need to incremement it each time we compute the numerical Jacobian
via differencing

for jacobian=3, fix RHS eval counter

---

integration/VODE/vode_dvjac.H
integration/VODE/vode_rhs.H
integration/VODE/vode_rhs_simplified_sdc.H

we should just store the RHS evals used in the advance, and not for
computing the numerical Jacobian

don't output state to nonaka plot file for Jacobian evaluation

---

unit_test/test_rhs/inputs_chamulak

This will be useful in evaluating the solution to #819.

Add test_rhs inputs for ignition_chamulak

---

EOS/helmholtz/actual_eos.H
interfaces/eos_type.H
unit_test/test_eos/eos_util.cpp

also fix test_react compilation for ztwd

put some EOS parameters in a namespace

---

sphinx_docs/source/integrators.rst

These changes remove references to Fortran, and update the reaction system to the one that is based on e instead of T. (Along with this, we also now point out that this e is the real internal energy instead of the tracer variable it was before.)

Update documentation on reaction ODE system

---

requirements.txt
sphinx_docs/source/basics.rst
sphinx_docs/source/conf.py
sphinx_docs/source/data_structures.rst
sphinx_docs/source/index.rst
sphinx_docs/source/networks-overview.rst
sphinx_docs/source/networks.rst

this is prep for adding details of the templated RHS

split the network docs across several pages

---

unit_test/test_sdc_vode_rhs/_parameters
unit_test/test_sdc_vode_rhs/inputs_aprox19
unit_test/test_sdc_vode_rhs/vode_rhs_test.H

this syncs up a bit with burn_cell_sdc -- maybe eventually they
can be merged?

add advective terms to test_sdc_vode_rhs

---

interfaces/burn_type.H

this makes the ordering match that of Strang

put species at the start of the simplified-SDC vector

---

unit_test/test_sdc_vode_rhs/vode_rhs_test.H

this needed updating for the new nets

fix compilation of test_sdc_rhs_vode

---

.github/workflows/burn_cell.yml
unit_test/burn_cell/README.md
unit_test/burn_cell/inputs_subch2
unit_test/burn_cell/subch2_unit_test.out

this will be able to tell us if we broke the execution
this uses a pynucastro net, and we can leverage this with
pynucastro CI to autogenerate the network there as well.

add a new action that runs burn_cell

---

Make.Microphysics_extern
screening/screen.H
screening/screen_data.H
unit_test/test_screening/GNUmakefile

This adds 2 new screening formulations based on [Chugunov, DeWitt, and Yakovlev 2007](https://journals.aps.org/prd/abstract/10.1103/PhysRevD.76.025028) and [Chugunov and DeWitt 2009](https://journals.aps.org/prc/abstract/10.1103/PhysRevC.80.014611) as discussed in #146.

Add new reaction rate screening routines

---

unit_test/test_screening/screening_util.cpp

Use new screening interface in test_screening

---

integration/VODE/actual_integrator.H
integration/VODE/actual_integrator_simplified_sdc.H
integration/VODE/vode_dvjac.H
integration/VODE/vode_rhs_simplified_sdc.H
integration/VODE/vode_type.H
util/linpack.H

also switch some ints to short to save memory

make the Jacobian type part of dvode_type

---

screening/screen.H

also remove the commented-out density derivatives in screen5

Template out T derivatives from screening methods

---

networks/ignition_reaclib/URCA-simple/reaclib_rate_metadata.dat
networks/ignition_reaclib/URCA-simple/reaclib_rates.H
networks/ignition_reaclib/URCA-simple/table_rates.H
networks/ignition_reaclib/URCA-simple/table_rates_data.cpp

updates `URCA-simple` network using latest pynucastro release.
This update addresses issue #952

update urca network

---

unit_test/test_nse/_parameters
unit_test/test_nse/burn_cell.H
unit_test/test_nse/inputs_aprox13
unit_test/test_nse/inputs_aprox19
unit_test/test_nse/inputs_aprox21
unit_test/test_nse/inputs_iso7
unit_test/test_nse/inputs_subch2

there is no sense of time in an NSE state, so eliminate the loop over time

simplify the NSE driver

---

unit_test/burn_cell/burn_cell.H
unit_test/burn_cell/ecsn_unit_test.out
unit_test/burn_cell/subch_approx_unit_test.out

we now output the t=0 RHS and the number of steps taken

update burn_cell with more info

---

interfaces/network_initialization.cpp
networks/ECSN/Make.package
networks/Make.package
networks/aprox13/Make.package
networks/aprox19/Make.package
networks/aprox21/Make.package
networks/general_null/Make.package
networks/ignition_chamulak/Make.package
networks/ignition_reaclib/C-burn-simple/Make.package
networks/ignition_reaclib/URCA-simple/Make.package
networks/ignition_simple/Make.package
networks/iso7/Make.package
networks/nova/Make.package
networks/nova2/Make.package
networks/partition_test/Make.package
networks/powerlaw/Make.package
networks/primordial_chem/Make.package
networks/rprox/Make.package
networks/sn160/Make.package
networks/subch_approx/Make.package
networks/subch_full/Make.package
networks/subch_simple/Make.package
networks/triple_alpha_plus_cago/Make.package
networks/vode_example/Make.package

we no longer need HAS_CXX_IMPLEMEMENTATION

---

EOS/helmholtz/actual_eos.H

this gets around some MPI issues with GPUs

read the helmtable into local memory, bcast, and then copy to managed

---

.github/workflows/cuda.yml
.github/workflows/dependencies_nvcc11.sh

this largely copies the AMReX CI, but updates to later Ubuntu and CUDA

add CUDA action

---

integration/ForwardEuler/_parameters
integration/ForwardEuler/actual_integrator.H

Also makes the timestepping a little stricter based on comparison with VODE.

Fix compilation for ForwardEuler integrator

---

integration/QSS/actual_integrator.H

These changes mostly prevent trace species from controlling the update.

Harden QSS integrator

---

integration/BackwardEuler/actual_integrator.H
integration/ForwardEuler/actual_integrator.H
integration/QSS/actual_integrator.H
integration/VODE/actual_integrator.H
interfaces/burn_type.H
unit_test/test_jac/jac_zones.H
unit_test/test_rhs/rhs_zones.H

remove the Strang self_heat parameter

---

integration/VODE/actual_integrator.H
integration/VODE/actual_integrator_simplified_sdc.H

sync up some code between Strang and SDC drivers

---

unit_test/burn_cell/burn_cell.H
unit_test/burn_cell/ci-benchmarks/ecsn_unit_test.out

we need to call the EOS before calling actual_rhs

fix an FPE in burn_cell

---

integration/VODE/vode_dvhin.H
integration/VODE/vode_dvode.H
integration/VODE/vode_type.H

this is a temporary fix until we actually refactor true SDC to only evolve (rho X, rho e)

fix true SDC compilation with VODE

---

integration/VODE/vode_dvjac.H
integration/integrator_rhs_simplified_sdc.H

this did parts of the Jacobian numerically and the conversion to energy analytically.  But it never seems to have been a big win, and maintaining this code path is not worth it.

remove jacobian = 3 option

---

interfaces/burn_type.H

we can use this to estimate the time to equilibriation for reactions

add dx back into the burn_t

---

sphinx_docs/source/nse.rst
sphinx_docs/source/refs.bib

add docs to explain the dynamic nse check according to kushnir's paper.

add docs for dynamic nse

---

sphinx_docs/source/refs.bib

things got scrambled in a merge commit

fix a bibtex ref

---

nse_solver/nse_solver.H
sphinx_docs/source/nse.rst
unit_test/test_ase/GNUmakefile
unit_test/test_ase/burn_cell.H
unit_test/test_ase/make_table/GNUmakefile
unit_test/test_ase/make_table/burn_cell.H

hide nse_state from in_nse() interface.

hide nse_state from in_nse() interface

---

integration/nse_update.H
interfaces/burner.H

this adds an "NSE_NET" branch to nse_update.H in the integrator

hook the self-consistent NSE into network integration

---

.github/workflows/compile_action.yml
.github/workflows/create_release.yml
.github/workflows/find_changed_files.py
.github/workflows/gh-pages.yml

in particular checkoutv3 is needed now
also, primordial_chem times out in the compilation test

update action versions to suppress warnings + skip primordial_chem

---

integration/nse_update.H
interfaces/burner.H
nse_solver/_parameters
nse_solver/nse_check.H
nse_solver/nse_solver.H
unit_test/test_nse/nse_example.H

fix compilation errors after including `NSE` preprocessor for self-consistent nse.

nse compilation fixes

---

integration/nse_update.H
networks/aprox19/_parameters
nse_solver/_parameters

we were not using this feature, and I don't think it's the correct approach

remove eta from tabular NSE

---

nse_solver/nse_check.H
nse_solver/nse_solver.H
util/hybrj/hybrj.H
util/hybrj/hybrj_dogleg.H
util/hybrj/hybrj_enorm.H
util/hybrj/hybrj_r1mpyq.H

1) Fixed some bugs in the NSE routine.
2) Fixed uninitialized variable issues caused by minpack hybrid solver.
3) Fixed erroneous arithmetic operations during hybrid solver due to NaN, INF and division by zero.

hybrj and NSE routine fix.

---

networks/aprox19/actual_network.H
networks/aprox21/actual_network.H
networks/iso7/actual_network.H

Clean up rate tabulation in aprox19, aprox21, and iso7

---

networks/ECSN/Make.package
networks/ECSN/actual_network.H
networks/ECSN/actual_rhs.H
networks/ECSN/partition_functions.H
networks/ECSN/reaclib_rates.H
networks/ECSN/table_rates.H
networks/ECSN/table_rates_data.cpp
networks/ECSN/tfactors.H
unit_test/burn_cell/ci-benchmarks/ecsn_unit_test.out

Update the ECSN network and bench mark test based on changes in  pynucastro/pynucastro#502

Update ECSN network and benchmark test

---

interfaces/eos_type.H

Value-initialize all members in eos_t & friends

---

nse_solver/nse_solver.H

use NET_NETWORK_IMPLEMENTATION instead

don't test on header guard presence

---

nse_solver/nse_solver.H

also store chemical potentials so `get_nse_state()` returns all information needed for nse calculations.

store chemical potentials to nse_state

---

integration/Make.package
integration/nse_update_simplified_sdc.H
integration/nse_update_strang.H
interfaces/burner.H

split nse_update.H into Strang and Simplified-SDC versions

---

networks/aprox19/nse_table.H

this can be expensive and unnecessary when we are iterating

allow us to optionally skip interpolating X from the NSE table

---

sphinx_docs/source/conf.py

add sphinx_rtd_theme to extensions, fix doc search.

fix search in doc

---

.github/workflows/gh-pages.yml

ubuntu-18.04 is deprecated and the build fails

---

.github/workflows/burn_cell_primordial_chem.yml
.github/workflows/find_changed_files.py

now that it is optimized, it no longer times out

add primordial chem back into the CI

---

integration/VODE/Make.package

vode_parameters does not exist

---

integration/BackwardEuler/be_integrator.H
integration/utils/numerical_jacobian.H

remove this from BackwardEuler, since now it is handled for us

update the numerical Jacobian to support disabling e and boosting

---

integration/BackwardEuler/actual_integrator.H
integration/BackwardEuler/actual_integrator_simplified_sdc.H
integration/BackwardEuler/be_integrator.H
integration/BackwardEuler/be_type.H
integration/QSS/actual_integrator.H
integration/RKC/actual_integrator.H
integration/RKC/actual_integrator_simplified_sdc.H
integration/RKC/rkc.H
integration/RKC/rkc_type.H

Template remaining integrators on number of equations

---

integration/BackwardEuler/actual_integrator.H
integration/ForwardEuler/actual_integrator.H
integration/Make.package
integration/QSS/actual_integrator.H
integration/RKC/actual_integrator.H
integration/VODE/actual_integrator.H
integration/integrator_type.H
integration/integrator_type_simplified_sdc.H
integration/integrator_type_strang.H

We start with the functions that don't conflict, and will follow up in future PRs with changes that harmonize the analogous functions and move them into integrator_type.H.

Start merging integrator_type

---

integration/RKC/actual_integrator_simplified_sdc.H

we come in with a valid e
this syncs us up with VODE

fix the thermodynamics in the RKC simplified-SDC

---

Make.Microphysics_extern

these include Make.Microphysics_extern
but not Make.Microphysics

fix compilation of application codes that use the NSE table

---

.github/workflows/hip.yml

Switch to a simpler approx net for HIP CI

---

EOS/primordial_chem/actual_eos.H

Added the calculation of pressure for the primordial chem EOS.

Compute pressure for primordial chem EOS

---

.github/workflows/cuda.yml

This adds CUDA coverage for tabular rates, partition functions, and self-consistent NSE.

Update CUDA compilation test to cover more cases

---

sphinx_docs/source/conf.py

fix the sphinx css includes

---

networks/ECSN/actual_network.H
networks/ECSN/actual_network_data.cpp
networks/ECSN/actual_rhs.H
networks/ECSN/partition_functions.H
networks/ECSN/reaclib_rates.H
networks/ECSN/table_rates.H

this will help us with the diffs in the pynucastro C++ CI
this does not change the benchmark.  Several PRs down the line will affect that.

update ECSN with latest pynucastro

---

unit_test/burn_cell_sdc/_parameters
unit_test/burn_cell_sdc/burn_cell.H

this fixes some valgrind issues

initialize ye, mu's for NSE_NET in burn_cell_sdc

---

networks/general_null/network_header.template

we already have it as a constexpr

we don't need NUM_EXTRA_SPECIES in the preprocessor

---

integration/BackwardEuler/be_integrator.H
integration/utils/initial_timestep.H

this avoids a name conflict with Castro

rename initial_dt() to initial_react_dt()

---

interfaces/burn_type.H

remove sdc_burn_to_eos

---

.editorconfig
.git-blame-ignore-revs
.github/workflows/style.yml
.github/workflows/style/check_tabs.sh
.github/workflows/style/check_trailing_whitespaces.sh

https://editorconfig.org/ has instructions on setting up your editor to follow the configured style.

Add AMReX style CI and EditorConfig file

---

.github/workflows/macos_build_cell_primordial_chem.yml

Fixes https://github.com/AMReX-Astro/Microphysics/issues/1352.

workaround macOS CI bug

---

util/linpack.H

This reverts commit 1f0c666f18c0418a3ab0aa817de00f8fd52ebac7.
This is an alternative to #1409 and seems to work better on frontier

revert reinterpret_cast in linalg.H

---

integration/VODE/actual_integrator.H

make sure const temperature evolution when call_eos_in_rhs=false

make sure const T evolution

---

.github/workflows/castro-development.yml

the current one tests against the same tag as Microphysics, so if we adapt something here to keep pace with AMReX, then we will fail the current test.

add another Castro action that tests against AMReX development

---

nse_tabular/nse_table_type.H

initialize nse_table_t members

---

nse_tabular/nse_eos.H
nse_tabular/nse_table.H
unit_test/test_nse_interp/ci-benchmarks/aprox19.out
unit_test/test_nse_interp/nse_cell.H

these mirror the existing interfaces for temperature

add NSE EOS interfaces for finding a consistent density

---

.github/workflows/check_powi.py
screening/screen.H

Fixed powi script to test for nested pow, I changed it so that it matches the inner most pow at a time and iterates over to replace all nested pows.
Also fix the bug introduced in chugunov2009 from the previous pr.

[WIP] fix powi script and bug in chugunov2009 screening

---

unit_test/test_react/inputs_reaclib_urca

the relative tolerances were very tight

update tols for Urca test_react so it runs

---

interfaces/burn_type.H

initialize the components of burn_t

---

unit_test/write_job_info.cpp

replace asctime -> strftime

---

EOS/breakout/actual_eos.H
EOS/gamma_law/actual_eos.H
EOS/helmholtz/actual_eos.H
EOS/multigamma/actual_eos.H
EOS/polytrope/actual_eos.H
EOS/primordial_chem/actual_eos.H
EOS/rad_power_law/actual_eos.H
EOS/tillotson/actual_eos.H
EOS/ztwd/actual_eos.H
interfaces/eos.H
nse_tabular/nse_table_check.H

is_same<>::value -> is_same_v<>

some clang-tidy modernize-type-traits

---

nse_tabular/nse_table.H
nse_tabular/nse_table_type.H
unit_test/nse_table_cell/nse_cell.H
unit_test/test_nse_interp/ci-benchmarks/aprox19.out
unit_test/test_nse_interp/nse_cell.H

we never use it and the interpolation can be expensive

remove dabardt from the NSE output

---

EOS/helmholtz/actual_eos.H
unit_test/test_linear_algebra/GNUmakefile
unit_test/test_linear_algebra/Make.package
unit_test/test_linear_algebra/README.md
unit_test/test_linear_algebra/_parameters
unit_test/test_linear_algebra/main.cpp
unit_test/test_linear_algebra/test_linear_algebra.H

this will test just the rhs.H routines for solving a linear system

create a linear algebra unit test

---

integration/BackwardEuler/actual_integrator.H
integration/BackwardEuler/actual_integrator_sdc.H
integration/RKC/actual_integrator.H
integration/RKC/actual_integrator_sdc.H
integration/VODE/actual_integrator.H
integration/VODE/actual_integrator_sdc.H
integration/VODE/vode_dvode.H

something changed upstream that we need to be more explicit now

fix compilation with amrex::Font

---

unit_test/test_screening_templated/GNUmakefile
unit_test/test_screening_templated/Make.package
unit_test/test_screening_templated/README
unit_test/test_screening_templated/_parameters
unit_test/test_screening_templated/inputs
unit_test/test_screening_templated/main.cpp
unit_test/test_screening_templated/screening_util.cpp
unit_test/test_screening_templated/test_screen.H
unit_test/test_screening_templated/variables.H
unit_test/test_screening_templated/variables.cpp

I've been using this to test out autodiff on the screening implementations.

Add a version of test_screening that works on any templated network

---

nse_solver/nse_check.H
util/microphysics_sort.H

this is intended to address AMReX-Astro/Castro#2818 as suggested by @WeiqunZhang

change quickSort to use iteration instead of recursion

---

nse_solver/make_table/burn_cell.H
unit_test/burn_cell/burn_cell.H
unit_test/burn_cell_primordial_chem/burn_cell.H
unit_test/burn_cell_sdc/burn_cell.H
unit_test/eos_cell/eos_cell.H
unit_test/nse_table_cell/nse_cell.H
unit_test/test_ase/burn_cell.H
unit_test/test_ase/make_table/burn_cell.H
unit_test/test_linear_algebra/test_linear_algebra.H
unit_test/test_nse/nse_example.H
unit_test/test_nse_interp/nse_cell.H
unit_test/test_part_func/pf_cell.H
unit_test/test_sdc_vode_rhs/vode_rhs_test.H

most adding inline to avoid ODR issues

fix some header issues identified by clang-tidy

---

.github/workflows/check_powi.yml
.github/workflows/docs-test.yml

don't cache pip if we don't pip install anything
fix check_powi action name

some fixes to actions

---

interfaces/eos_type.H

add an eos_rh_t for MAESTROeX

---

integration/nse_update_sdc.H

fix drhoauxdt declaration

---

util/build_scripts/write_probin.py

sort the entries in the runtime parameter struct by type

---

Make.Microphysics_extern
interfaces/network_initialization.cpp
networks/aprox19/actual_network.H
nse_tabular/README.md

this fixes table initialization and linking with nets other than aprox19.  The instructions are also updated.

some generalization of the NSE table stuff

---

sphinx_docs/source/autodiff.rst
util/microphysics_autodiff.H

This can calculate derivatives with respect to multiple variables in a single pass.

Add `autodiff::dual_array`

---

unit_test/test_nse_net/burn_cell.H
unit_test/test_nse_net/ci-benchmarks/nse_net_unit_test.out

this follows the same test that is done in the test_nse_interp test.

update the test_nse_net test  to also test the NSE EOS

---

integration/integrator_setup_sdc.H
integration/integrator_setup_strang.H

if we are on the GPU with printf allowed, we weren't backing up the thermo state

fix some burn failure diagonstics on GPUs

---

integration/integrator_rhs_sdc.H
integration/integrator_rhs_strang.H
integration/utils/numerical_jacobian.H

the MathArray2D is Fortran-ordered.  Some of the loops should be more efficient if their order is swapped.

reorder some loops over Jacobians

---

integration/BackwardEuler/be_integrator.H

the MathArray is Fortran-ordered

fix the loop order over Jac in BackwardEuler

---

.github/workflows/macos_build_cell_metal_chem.yml
.github/workflows/macos_build_cell_primordial_chem.yml

Homebrew changes in strange and mysterious ways. I think this will get it working again.

Fix macOS CI

---

CITATION.md
Docs/Makefile
Docs/source/citing.rst
Docs/source/conf.py
Docs/source/index.rst
requirements.txt

also clean up the conf.py script a bit with the linter

add a CITATION.md and a citing page to the docs

---

.gitignore
CHANGES.md
Docs/Makefile
Docs/parse_changelog.py
Docs/source/changes.rst
Docs/source/conf.py
Docs/source/index.rst

this also now makes the changelog part of the docs with links to the PRs.

fix some markdown in CHANGES.md and add some more PR refs

---

.github/workflows/dependencies/dependencies_hip.sh
.github/workflows/hip.yml

this syncs the dependency script up with amrex

update hip action -- ubuntu 20.04 runner is going away

---

Make.Microphysics

this no longer seems to be available

remove make stuff for sparse jacobian

---

Make.Microphysics

this was removed from AMReX in 21.10

remove the CRSEGRNDOMP macro

---

requirements.txt

it seems that nbsphinx is not yet compatible with Sphinx 8.2.0

require Sphinx < 8.2.0

---

unit_test/test_react/inputs_nova

with the update to nova net, we need to tweak the test_react inputs

---

Docs/source/build_system.rst
Docs/source/data_structures.rst
Docs/source/eos.rst
Docs/source/eos_implementations.rst
Docs/source/networks-overview.rst
Docs/source/refs.bib

this is a read through up to ODEs

some fixes to the docs

---

integration/integrator_type_sdc.H
interfaces/burner.H

also get rid of the strang version `nse_burn` call in burner.

allow constant temperature for sdc burn.

---

paper/paper.bib
paper/paper.md

A set of updates to the text:
- Revises the display style of my author name
- Fixes a spelling typo
- Adds a sentence with two citations to ML papers using this Microphysics library to the Statement of Need.
- Adds a footnote explaining our choice to use an alphabetical author list for the development team members.

My Updates

---

networks/general_null/network_header.template
networks/general_null/write_network.py

also remove legacy language checks in the script

specify the type for some network properties enums
